### ISSUE TITLE
[Bug] 管理员名单不统一

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#100]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在前端脚本上的管理员名单里面，但并没有在后台的管理员权限里，所以应当把我的前端权限删除

**Comment by langningchen** [comment]
#100 :tada:

**Comment by boomzero** [comment]
Dev已经删了

你不用dev吗?
/invalid

**Comment by langningchen** [comment]
> Dev已经删了
> 
> 你不用dev吗?

@boomzero 我手机版本用的是发布版，电脑上用的是预览版
