### ISSUE TITLE
[Bug] 自动提交当年代码无法提交

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#107]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

只是提交到了该题目，而不是该比赛中的该题目，所以导致提交了但是没有算入成绩

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/9d052175-710c-4463-bf2f-91cb5043eb37)

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/463c24c4-5df3-4e63-9d1c-b8db4791e86c)

~~昨天没上课，没做题，别管~~

**Comment by langningchen** [comment]
不应该用 `id=` 而应该用 `cid=&pid=` @boomzero

**Comment by boomzero** [comment]
无法复现

**Comment by boomzero** [comment]
我用的cid啊

**Comment by boomzero** [comment]
> 不应该用 `id=` 而应该用 `cid=&pid=` @boomzero

哦懂了

**Comment by langningchen** [comment]
这个得看运气

**Comment by langningchen** [comment]
还有如果你碰到了 @PythonSmall-Q 别忘了告诉他他的服务器炸了一个

**Comment by langningchen** [comment]
他的那个 `[GitHub Download3](https://stats.uptimerobot.com/qWQnZT1M6Z/794396354)` 炸了

**Comment by boomzero** [comment]
我知道为什么

**Comment by boomzero** [comment]
测试一下 @langningchen

**Comment by langningchen** [comment]
没事，我看了代码应该是对的

**Comment by boomzero** [comment]
thx

**Comment by boomzero** [comment]
referrer呢

**Comment by boomzero** [comment]
done

**Comment by boomzero** [comment]
@langningchen ~你不也用这个功能吗~

**Comment by langningchen** [comment]
@boomzero 这不是使用，这是测试 doge
