### ISSUE TITLE
[Bug] 在已结束的比赛提交时显示正确错误信息

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#116]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by PythonSmall-Q** [comment]
这个，错误信息没问题吧。

**Comment by PythonSmall-Q** [comment]
比赛不存在没错呀

**Comment by boomzero** [comment]
会提交失败

**Comment by PythonSmall-Q** [comment]
对呀，是提交失败

**Comment by boomzero** [comment]
应该显示比赛已结束, 自动提交当年代码也要报错

**Comment by PythonSmall-Q** [comment]
fixed
