### ISSUE TITLE
[Feature Request] 预编译使用C++14

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#118]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

http://www.xmoj.tech/discuss3/thread.php?tid=219&page=3

**Comment by PythonSmall-Q** [comment]
@boomzero 之后用
```
/fixed
```来close

**Comment by boomzero** [comment]
Why?

**Comment by PythonSmall-Q** [comment]
/              fixed

**Comment by PythonSmall-Q** [comment]
我写的命令，但是现在会remove所有的badge

**Comment by boomzero** [comment]
Label.
