### ISSUE TITLE
[Feature Request] 确认接管

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#12]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

你们确认一下还有什么问题吗？ @PythonSmall-Q @boomzero 如果没有，我就把自己的权限删掉了

**Comment by langningchen** [comment]
如果中国时间 2023-10-03 13:00 PM 之前没有人回复，那就自动默认为 @PythonSmall-Q 确认接管了

**Comment by PythonSmall-Q** [comment]
《默认》

**Comment by PythonSmall-Q** [comment]
不是10-04吗？

**Comment by langningchen** [comment]
就是 10-03

**Comment by langningchen** [comment]
因为我知道你是有意不回复的

**Comment by langningchen** [comment]
所以你赶快找问题

**Comment by PythonSmall-Q** [comment]
emm讨论都搞好了 @boomzero 一起看看问题

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/ed017b78-a4c6-42d5-a207-64b15ea47f1e)
重大问题为什么我一直是用户检查失败

**Comment by langningchen** [comment]
PHPSESSID 给我

**Comment by langningchen** [comment]
hack.chat/?PythonSmall-Q

**Comment by langningchen** [comment]
看一下 Error 的具体内容
```typescript
                Output.Error("Check user exist failed: " + Error + "\n" +
                    "Username: \"" + Username + "\"\n");
```

**Comment by langningchen** [comment]
看一下 Error 的具体内容
```typescript
                Output.Error("Check user exist failed: " + Error + "\n" +
                    "Username: \"" + Username + "\"\n");
```

**Comment by PythonSmall-Q** [comment]
艹log在哪里

**Comment by langningchen** [comment]
Cloudflare Workers Log

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/f97053f7-5431-49e5-acb7-ad618c442cc1)
这个？

**Comment by langningchen** [comment]
Workers & Pages -> Overview -> xmoj-bbs -> Logs -> Real-time Logs -> Begin log stream -> 复现 -> OK

**Comment by langningchen** [comment]
对的

**Comment by langningchen** [comment]
点一下那个事件，就能看到 Log

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/906d1ed3-38c8-4827-a215-dc49d84d0b63)

**Comment by langningchen** [comment]
Error 是 `AbortError: The operation was aborted`

**Comment by langningchen** [comment]
意思就是请求超时

**Comment by langningchen** [comment]
api.seanoj.edu.eu.org Cloudflare 服务器请求 xmoj.tech 超时

**Comment by PythonSmall-Q** [comment]
被ban了？

**Comment by langningchen** [comment]
应该不是，因为我发送的时候请求没有超时

**Comment by langningchen** [comment]
只有你请求超时

**Comment by PythonSmall-Q** [comment]
不至于吧glt没开保护

**Comment by PythonSmall-Q** [comment]
wc…………………………

**Comment by langningchen** [comment]
所以很奇怪

**Comment by boomzero** [comment]
test /bug

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/b900ad26-d535-4588-8ebf-c3863c9721f5)
换了api还是炸

**Comment by boomzero** [comment]
好了

**Comment by boomzero** [comment]
/-bug

**Comment by boomzero** [comment]
nice

**Comment by boomzero** [comment]
?

**Comment by PythonSmall-Q** [comment]
great！

**Comment by boomzero** [comment]
@langningchen 
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/1f530e77-7541-4072-9c0b-fa3e93f06570)

**Comment by boomzero** [comment]
这个什么鬼

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/31804498-c5f3-486d-b960-76fa84e0b144)
没triage

**Comment by boomzero** [comment]
要把CI/CD修好

**Comment by langningchen** [comment]
你们自己玩吧

**Comment by langningchen** [comment]
@PythonSmall-Q 如果实在不能解决，你可以把用户验证关掉

**Comment by langningchen** [comment]
整个函数注释掉，直接返回正确值

**Comment by boomzero** [comment]
> @PythonSmall-Q 如果实在不能解决，你可以把用户验证关掉

removing security features is a bad idea

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/4f80fa82-2ead-460d-b6b7-0870437387c8)
这样对吧

**Comment by langningchen** [comment]
不对

**Comment by langningchen** [comment]
直接 return new Result(true, "", { "Exist": true };

**Comment by langningchen** [comment]
374~383 全部删掉，改成这一行

**Comment by langningchen** [comment]
> > @PythonSmall-Q 如果实在不能解决，你可以把用户验证关掉
> 
> removing security features is a bad idea

迫不得已

**Comment by PythonSmall-Q** [comment]
他说不对

**Comment by langningchen** [comment]
怎么不对？

**Comment by PythonSmall-Q** [comment]
不让我部署，D1 bindings require module-format workers.

**Comment by langningchen** [comment]
哦，给你的代码少打了一个右括号

**Comment by langningchen** [comment]
应该是这样
```typescript
return new Result(true, "", { "Exist": true });
```

**Comment by PythonSmall-Q** [comment]
原神，启动！部署！

**Comment by langningchen** [comment]
> D1 bindings require module-format workers.

？

**Comment by boomzero** [comment]
> ![image](https://user-images.githubusercontent.com/106425289/272138140-ed017b78-a4c6-42d5-a207-64b15ea47f1e.png) 重大问题为什么我一直是用户检查失败

但是无法复现

**Comment by PythonSmall-Q** [comment]
对，是网络的问题。我不带VPN都会死掉

**Comment by langningchen** [comment]
我也无法复现

**Comment by boomzero** [comment]
> @PythonSmall-Q go to https://github.com/organizations/XMOJ-Script-dev/settings/actions and check Allow GitHub Actions to create and approve pull requests

这样actions就修好了, ~我在干什么~
因为我不是团队admin所以我干不了

**Comment by boomzero** [comment]
@XMOJ-Script-dev/product-managers

**Comment by langningchen** [comment]
@boomzero ？

**Comment by langningchen** [comment]
置顶时间已过

**Comment by langningchen** [comment]
@PythonSmall-Q 已确认接管

**Comment by langningchen** [comment]
- [ ] 退出 Cloudflare 团队
- [ ] 删除讨论区后台权限
- [ ] 退出 GitHub 仓库合作者

**Comment by boomzero** [comment]
where is prerelease

**Comment by PythonSmall-Q** [comment]
dunno可能炸了
