### ISSUE TITLE
[Feature Request] 预编译检查项目增加

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#120]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

除了检查编译错误和文件输入输出之外，还可以检查一下开的空间有没有爆炸，因为有很多人傻傻分不清，闭着眼开了个1e8以上的数组然后就MLE喜提零分，我觉得太可惜了，可以开发一个功能来辨别程序中开的空间有没有溢出
——credits：shihongxi

**Comment by PythonSmall-Q** [comment]
@boomzero 你看行不行

**Comment by boomzero** [comment]
Hmm, 开多了不是会CE吗

**Comment by boomzero** [comment]
这不好, 到时候你CSP这样做直接boomzero

**Comment by boomzero** [comment]
平时还是要锻炼的
