### ISSUE TITLE
[Feature Request] 抄std的给badge作弊者

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#121]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

还有既然有了查看标程这个功能，有很多偷懒的人就直接递交标程了，这个就像在洛谷社区中直接抄袭题解一样性质恶劣，在洛谷中，多次抄袭题解会给予作弊者的棕名惩罚，我觉得在xmoj平台上也可以有相应的惩罚，你可以把他的代码和查看标程中的程序进行对比，像查重一样得到程序的相似度，如果相似度太高了就给他作弊者的badge，我认为这个功能的主要目的就是防止某些人一直经常地抄袭标程，一定得严惩！
——Credits：shihongxi

**Comment by PythonSmall-Q** [comment]
@boomzero 你看呢？

**Comment by boomzero** [comment]
可以, 虽然抄std没用任何意义

**Comment by PythonSmall-Q** [comment]
那等有空了做吧

**Comment by PythonSmall-Q** [comment]
感觉没必要，但是可以考虑把疑似抄袭当年代码变成作弊者
