### ISSUE TITLE
[Feature Request] 增加奖励机制鼓励用户发言

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#124]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

例如积分等：
- 回复一次 1 积分
- 发帖一次 3 积分
- 签到一次 2 积分（连续签到积分更多）
- AC题目一道 5 积分
- 等等

对应的奖励：
- 100 积分获得查看标程（即使50分以下）权限一次
- 300 积分获得一日 Badge 体验 
- 1000 积分获得固定颜色 Badge
- 5000 积分获得任意颜色（除紫色外） Badge
- 等等

### 原因

用户使用不积极

**Comment by langningchen** [comment]
对于这种，服务器也只是需要保存一下积分的数值就好了，数据表可以与 #63 合并

**Comment by PythonSmall-Q** [comment]
可以考虑

**Comment by langningchen** [comment]
你要 “考虑” 多久？ @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
加入队列末尾

**Comment by boomzero** [comment]
fake internet points!

**Comment by boomzero** [comment]
At this point, we might as well write our own OJ

**Comment by boomzero** [comment]
> At this point, we might as well write our own OJ

/wontfix

**Comment by langningchen** [comment]
@PythonSmall-Q ？？？

**Comment by boomzero** [comment]
@langningchen , well, I did tell @hendragon-bot wontfix...

**Comment by boomzero** [comment]
Ok, new idea:

we will award users if they upload std

**Comment by boomzero** [comment]
And this new value(I'd like to call it `rp`) is added to a user's rating

**Comment by PythonSmall-Q** [comment]
我们是不是可以考虑一下做一个签到，这样增加互动效果。但是我觉得我们应该先在首页加入一个最近讨论板块

**Comment by PythonSmall-Q** [comment]
这样的话或许讨论的人数可以多一点

**Comment by boomzero** [comment]
-/wontfix /enhancement

**Comment by PythonSmall-Q** [comment]
不干，否则成水池了（像洛谷一样
