### ISSUE TITLE
[Bug] 提交按钮渲染失败 & {部分题目讨论按钮消失(fixed) & 题目标题显示有误(fixed)}

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#138]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/3a2f0653-a00c-4bc6-9c2c-6b3bb0da5224)

**Comment by PythonSmall-Q** [comment]
@boomzero 是不是你干的

**Comment by boomzero** [comment]
Of course not

**Comment by boomzero** [comment]
讨论按钮没了

**Comment by boomzero** [comment]
我早就发现了, 只是没开issue

**Comment by boomzero** [comment]
我现在没时间写, 你来吧

**Comment by PythonSmall-Q** [comment]
![](https://api.xmoj-bbs.tech/GetImage?ImageID=lhnoytpyeuheoghzfigjwjxsajiqpxfh)  reject！

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/0f774a5f-2d36-4d53-9c92-5de9f7ed7764)
reject

**Comment by PythonSmall-Q** [comment]
@boomzero 以后别用这种东西轰炸我的email，你还发了两次请求

**Comment by PythonSmall-Q** [comment]
开始处理堆积如山的issue

**Comment by PythonSmall-Q** [comment]
去搞whk了。issue暂停

**Comment by boomzero** [comment]
+1

**Comment by PythonSmall-Q** [comment]
欸奇怪了xmoj前端没修改过呀 /help-wanted

**Comment by boomzero** [comment]
@langningchen why?

我看了一眼, 一堆`document.queryselector is null`

**Comment by langningchen** [comment]
可能是xmoj改了 doge

**Comment by langningchen** [comment]
确实是因为 xmoj 改了

**Comment by boomzero** [comment]
> 确实是因为 xmoj 改了

az, 6

**Comment by boomzero** [comment]
@XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers @XMOJ-Script-dev/product-managers 
@PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q @PythonSmall-Q 

快写

**Comment by PythonSmall-Q** [comment]
啊啊啊啊我很忙啊啊啊啊啊

**Comment by PythonSmall-Q** [comment]
我还在处理锁定的事情

**Comment by PythonSmall-Q** [comment]
要不你来写吧救命喵呜 @boomzero

**Comment by PythonSmall-Q** [comment]
嗯发文了：http://www.xmoj.tech/discuss3/thread.php?tid=239 @boomzero 加油qwq

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/147

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
cosmetic

**Comment by boomzero** [comment]
Fixed
