### ISSUE TITLE
[Bug] test

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#14]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

test

**Comment by boomzero** [comment]
test

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
@PythonSmall-Q 为什么我不能triage issue

**Comment by PythonSmall-Q** [comment]
treiage

**Comment by PythonSmall-Q** [comment]
和langningchen之前的一样，我是owner，你是member

**Comment by PythonSmall-Q** [comment]
《歧视》

**Comment by boomzero** [comment]
> 和langningchen之前的一样，我是owner，你是member

.

**Comment by boomzero** [comment]
~但是这个repo是我创建的~

**Comment by langningchen** [comment]
^

**Comment by langningchen** [comment]
……

**Comment by langningchen** [comment]
还有你们到底用哪一个？ XMOJ-Script-dev 的还是 PythonSmall-Q 的

**Comment by PythonSmall-Q** [comment]
dev。我在切换。但是出现了一些小bug

**Comment by PythonSmall-Q** [comment]
尝试做302

**Comment by PythonSmall-Q** [comment]
/-investigating
