### ISSUE TITLE
[Bug] 开发者渠道无法接受更新！

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#141]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/bca50be0-9426-4bae-9438-8af3f7821768)

如图所示，被跨域拦截掉了，这个也导致 AddonScript 无法被加载，所以除非用户意识到问题，手动重新安装，否则将会失去部分用户，我们也无法提醒他们需要手动更新

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 这个问题比较严重

**Comment by boomzero** [comment]
这个, 应该是 @PythonSmall-Q 关掉了pages

**Comment by PythonSmall-Q** [comment]
哈》和我有啥关系/当时转repo的时候大概没忘记改了

**Comment by PythonSmall-Q** [comment]
对呀，开发者模式肯定是没办法更新的。有没有人在用

**Comment by langningchen** [comment]
我搞错了，是 **开发者** 才通过 GitHub Pages 更新， **非开发者** 是 Cloudflare Pages 更新

**Comment by PythonSmall-Q** [comment]
正常人都是非开发者模式

**Comment by langningchen** [comment]
那就没这么重要了，我搞反了

**Comment by PythonSmall-Q** [comment]
嘶我看看能不能限制开发者模式

**Comment by PythonSmall-Q** [comment]
/-priority-high

**Comment by langningchen** [comment]
？为什么 invalid

**Comment by langningchen** [comment]
确实没法更新啊

**Comment by PythonSmall-Q** [comment]
/-invalid /bug /investigating

**Comment by PythonSmall-Q** [comment]
这个是由于repo转了，所以就会github pages就炸了 @langningchen

**Comment by PythonSmall-Q** [comment]
个人觉得没必要修复

**Comment by langningchen** [comment]
但是怎么更新？

**Comment by PythonSmall-Q** [comment]
emm没人再用开发模式

**Comment by PythonSmall-Q** [comment]
还是感觉问题不大。close了 /wontfix
