### ISSUE TITLE
[Bug]后台不检测帖子是否锁定

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#142]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/992abd81-1eac-4ba5-be81-5fe9fa5657b2)
但是我也不知道为什么shihongxi能发言qwq

**Comment by PythonSmall-Q** [comment]
@boomzero 顺便告知一下，用户检查去掉了我这里死也出发不了用户检查

**Comment by boomzero** [comment]
> @boomzero 顺便告知一下，用户检查去掉了我这里死也出发不了用户检查

...

**Comment by PythonSmall-Q** [comment]
没法复现

**Comment by langningchen** [comment]
？

**Comment by langningchen** [comment]
我试试

**Comment by PythonSmall-Q** [comment]
我去问shihongxi了

**Comment by PythonSmall-Q** [comment]
现在在写题

**Comment by langningchen** [comment]
不是，可能是 @boomzero 乱改了数据库

**Comment by langningchen** [comment]
把他的锁定时间改了

**Comment by PythonSmall-Q** [comment]
……

**Comment by PythonSmall-Q** [comment]
那也不是会锁定的吗

**Comment by PythonSmall-Q** [comment]
我昨天试了好几遍都发不了

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/b6f24d89-0c9b-48e8-93df-5f03659ad8f5)

嘿嘿，发言成功

**Comment by langningchen** [comment]
应该是在 NewReply 的处理中没有判断是否讨论已经锁定了，只是在前端把回复关了

**Comment by PythonSmall-Q** [comment]
啊，崩

**Comment by PythonSmall-Q** [comment]
事情又多了

**Comment by PythonSmall-Q** [comment]
顺便提一嘴，我把xmoj.flarum.cloud关了

**Comment by langningchen** [comment]
好吧

**Comment by langningchen** [comment]
这个很好改的

**Comment by PythonSmall-Q** [comment]
等我有空了改，刚月考完抑郁了

**Comment by langningchen** [comment]
我月考也考砸了

**Comment by langningchen** [comment]
Emm

**Comment by langningchen** [comment]
真的废了，物理连60都没上，化学才43……

**Comment by PythonSmall-Q** [comment]
我们还没出成绩但是语文炸了

**Comment by PythonSmall-Q** [comment]
hh我化学48，数学129其他的还没出

**Comment by langningchen** [comment]
语文数学英语都明天才出

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/90d1d44a-b6b3-4823-911e-0196ae78b5c1)
kkk名言

**Comment by langningchen** [comment]
> hh我化学48，数学129其他的还没出

你们数学卷子很难吗？

**Comment by PythonSmall-Q** [comment]
还好，有几道题计算错了

**Comment by langningchen** [comment]
#include <bits/stdc++.h>
using namespace std;
int main()
{
    cout << "Hello world" << endl;
    return 0;
}

**Comment by langningchen** [comment]
> 还好，有几道题计算错了

你们学到哪了？

**Comment by PythonSmall-Q** [comment]
圆之前，圆其中之后学

**Comment by PythonSmall-Q** [comment]
24个issue（炸了

**Comment by PythonSmall-Q** [comment]
早知道不说“加上你的名字”那句了，估计他就是这么做的

**Comment by langningchen** [comment]
> 圆之前，圆其中之后学

你们这种好学校就是学得快，我们严格按照进度学

**Comment by langningchen** [comment]
> 早知道不说“加上你的名字”那句了，估计他就是这么做的

确实

**Comment by langningchen** [comment]
> 24个issue（炸了

快点啊

**Comment by PythonSmall-Q** [comment]
最近抑郁了，决定先搞whk和复赛，issues等心情好了处理

**Comment by langningchen** [comment]
现在25个了

**Comment by PythonSmall-Q** [comment]
估计下周五找同学贴贴心情就好了

**Comment by langningchen** [comment]
> 估计下周五找同学贴贴心情就好了

？

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/6d049eaa-4d20-416e-ae20-e119f1e686f5)

**Comment by langningchen** [comment]
@PythonSmall-Q 我们英语老师在学 9A U3 的 WordBox 时竟然说 cute 一般不形容男生，我觉得她说的很不对

**Comment by PythonSmall-Q** [comment]
emm也不是不可以

**Comment by PythonSmall-Q** [comment]
我知道你是什么意思

**Comment by langningchen** [comment]
> 我知道你是什么意思

我是什么意思？

**Comment by langningchen** [comment]
doge

**Comment by PythonSmall-Q** [comment]
我有没有公开我的性别，你怎么知道不能用cute doge

**Comment by boomzero** [comment]
> 不是，可能是 @boomzero 乱改了数据库

没有...

**Comment by boomzero** [comment]
我都没怎么登cloudflare

**Comment by boomzero** [comment]
> 我有没有公开我的性别，你怎么知道不能用cute doge

...

**Comment by boomzero** [comment]
> hh我化学48，数学129其他的还没出

md我数学120

**Comment by PythonSmall-Q** [comment]
哇boomzero上线了

**Comment by boomzero** [comment]
@PythonSmall-Q 推荐你用copilot

**Comment by PythonSmall-Q** [comment]
err不想认证

**Comment by langningchen** [comment]
> 我有没有公开我的性别，你怎么知道不能用cute doge

没有公开？应该像我这样 @PythonSmall-Q 

![IMG_20231015_195155](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/4414a316-1a35-4d7f-b7fc-0db0a0e28663)
![IMG_20231015_195344](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/4a988168-497a-4096-9359-51bd3edbc2fa)

**Comment by boomzero** [comment]
@langningchen ~那我可以把我的pronoun 改为cln吗~

**Comment by langningchen** [comment]
> @langningchen ~那我可以把我的pronoun 改为cln吗~

可以啊，随便你

**Comment by langningchen** [comment]
你现在的是 `it` @boomzero

**Comment by langningchen** [comment]
我whk废了，复赛也没什么信心

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 你们月考多少分？

语文121, 数学120, 英语139, 物理66, 化学90 / 100

**Comment by boomzero** [comment]
但是神奇的是年级排名是34 / about 270

**Comment by boomzero** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/e6737fb9-2bac-4564-8096-9b10dbba156c)
emm...

**Comment by langningchen** [comment]
> > @boomzero @PythonSmall-Q 你们月考多少分？
> 
> 语文121, 数学120, 英语139, 物理66, 化学90 / 100

你们初二就开始学化学？？？我和 @PythonSmall-Q 都已经初三了......

**Comment by boomzero** [comment]
只是因为题目太多50分放不下

**Comment by langningchen** [comment]
> ~tmd我初三~

啊？是吗？

**Comment by langningchen** [comment]
> 只是因为题目太多50分放不下

好吧

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 问题加重！编辑好像也没鉴权！

![Screenshot_20231019_190933_Kiwi Browser](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/82f18340-5575-49ca-834b-f0e7854cb8dc)

**Comment by langningchen** [comment]
这个issue三分钟搞定，而且也很严重，耽误不了你们多长时间的

**Comment by langningchen** [comment]
另外， shihongxi 没有进行过任何开发操作，不得列入开发组名单

**Comment by langningchen** [comment]
只是进行过贡献

**Comment by boomzero** [comment]
他是admin...

**Comment by boomzero** [comment]
shanwenxiao改的

**Comment by boomzero** [comment]
> 另外， shihongxi 没有进行过任何开发操作，不得列入开发组名单

但是这个shanwenxiao说的算

**Comment by PythonSmall-Q** [comment]
是我加的编辑

**Comment by PythonSmall-Q** [comment]
Emm

**Comment by PythonSmall-Q** [comment]
不是bug

**Comment by langningchen** [comment]
> 是我加的编辑

好吧，是你随便改了数据库是吧

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/6a717587-d963-4919-aeca-efa27c952579)
zhineng

**Comment by PythonSmall-Q** [comment]
@langningchen 没限制你

**Comment by langningchen** [comment]
> @langningchen 没限制你

为什么要给我特判？

**Comment by langningchen** [comment]
@PythonSmall-Q 如果你没有 WSL 以后就别改要改服务器的代码了，要改服务器的 issue 让 @boomzero 改

**Comment by langningchen** [comment]
不然你提交不了更改的代码

**Comment by PythonSmall-Q** [comment]
我能提交的。

**Comment by PythonSmall-Q** [comment]
我甚至都成功了

**Comment by boomzero** [comment]
还是macOS好(

**Comment by PythonSmall-Q** [comment]
问题又出现了

**Comment by boomzero** [comment]
fixed
