### ISSUE TITLE
[Bug] 没有申请修改 Badge 的地方

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#146]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

并且提示消息显示不出来

---

开发者回复：暂时恢复了badge修改功能，后续会优化badge

**Comment by PythonSmall-Q** [comment]
对，我删的

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/9ddc0b51-e341-41a5-a906-cebbd08446d8)

**Comment by langningchen** [comment]
好吧……

**Comment by langningchen** [comment]
但是没有申请的地方，况且只删了前端，后端没删，所以没有用

**Comment by PythonSmall-Q** [comment]
没有申请，emm那就让他们短消息申请

**Comment by PythonSmall-Q** [comment]
《毒瘤》

**Comment by boomzero** [comment]
@PythonSmall-Q 能不能只允许修改文字吗

**Comment by PythonSmall-Q** [comment]
我到时候看看吧，等我心情好了

**Comment by langningchen** [comment]
> 我到时候看看吧，等我心情好了

去跟 aya 贴贴，说不定能擦出火花，然后心情就好了

**Comment by PythonSmall-Q** [comment]
> @PythonSmall-Q 能不能只允许修改文字吗

如果你有思路的话你做吧

**Comment by PythonSmall-Q** [comment]
@langningchen @boomzero 顺便说一下，新开发组成员shihongxi

**Comment by langningchen** [comment]
> @langningchen @boomzero 顺便说一下，新开发组成员shihongxi

真好，他会多少？

**Comment by Leiwenda** [comment]
来冒个泡（来自 @langningchen ）

**Comment by langningchen** [comment]
话说 shihongxi 的 GitHub 账号是哪个？

**Comment by langningchen** [comment]
@PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
还没加入，别急

**Comment by PythonSmall-Q** [comment]
> 来冒个泡（来自 @langningchen ）

？？？

**Comment by PythonSmall-Q** [comment]
目前暂时复原了badge修改功能

**Comment by PythonSmall-Q** [comment]
> 话说 shihongxi 的 GitHub 账号是哪个？

聊天记录：
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/2b88d5e5-0a12-4bc8-ba67-9a254a80969f)
《阅而不回》

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by PythonSmall-Q** [comment]
喜闻乐见，现在page1快都是站务版的东西了，可见我发帖频率多高
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/27efb82f-ea18-41e7-8fc8-9c85cf145c99)
page2大部分也是站务版
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/d5a4a3f0-20dd-42e2-aed8-265736de257c)

**Comment by boomzero** [comment]
> > @langningchen @boomzero 顺便说一下，新开发组成员shihongxi
> 
> 真好，他会多少？

Great...

**Comment by boomzero** [comment]
要是copliot 能直接帮我解决issue就好了...

**Comment by langningchen** [comment]
> 要是copliot 能直接帮我解决issue就好了...

我就都是用的 Copilot

**Comment by langningchen** [comment]
> ？？？

那一条是我登录的他的账号帮他发的

**Comment by boomzero** [comment]
> > ？？？
> 
> 那一条是我登录的他的账号帮他发的

...

**Comment by langningchen** [comment]
> ~我有他的password, 因为我翻过database~

好吧，那么加密短消息又要重新提起？

**Comment by boomzero** [comment]
不要

**Comment by boomzero** [comment]
> > ~我有他的password, 因为我翻过database~
> 
> 好吧，那么加密短消息又要重新提起？

added!
