### ISSUE TITLE
[Bug] 部分题目状态页没有运行编号

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#148]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/468e7e16-c078-4c8a-8a1d-f6093d3f484e)

**Comment by PythonSmall-Q** [comment]
还是xmoj改版的问题

**Comment by PythonSmall-Q** [comment]
讨论按钮之前的issue上报过了

**Comment by boomzero** [comment]
> 还是xmoj改版的问题

AC的题目应该没有

**Comment by langningchen** [comment]
我真是服了你们了，啥 Issue 都不管 @boomzero @PythonSmall-Q

**Comment by boomzero** [comment]
在CSP前我没时间修issue
