### ISSUE TITLE
[Bug] fix all actions

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#15]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
@PythonSmall-Q go to  https://github.com/organizations/GXMOJ-Script-dev/settings/actions  and check Allow GitHub Actions to create and approve pull requests

**Comment by boomzero** [comment]
@PythonSmall-Q go to https://github.com/organizations/XMOJ-Script-dev/settings/actions and check Allow GitHub Actions to create and approve pull requests

**Comment by boomzero** [comment]
@XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q @XMOJ-Script-dev/product-managers @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
done

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by boomzero** [comment]
> done

thx

**Comment by boomzero** [comment]
还有那个read and write permissions @PythonSmall-Q

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/e81435d7-f2ef-4b41-ae1f-e278e25d6f61)
fixed

**Comment by boomzero** [comment]
thz

**Comment by boomzero** [comment]
fixed, I think

**Comment by boomzero** [comment]
?

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by PythonSmall-Q** [comment]
@boomzero 一定要用指令

**Comment by PythonSmall-Q** [comment]
/-investigating
