### ISSUE TITLE
[Feature Request] 题目颜色

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#150]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

您可以结合这道题目的正确AC率和解出来的人数来评级，如果是这堂课新增的题目，我觉得可以通过脚本中的统计功能算出这道题的AC人数，再结合上课做题的人数，就能知道在多少人中游多少人解出了这道题目，也可以结合递交人数与AC人数与WA与TLE等不同状态的比例来衡量难易度，再像洛谷一样标注颜色和入门~普及~...的badge，这样就可以实现一个重要的功能，当然也可以手动加一些题目的badge！

**Comment by PythonSmall-Q** [comment]
credits：shihongxi

**Comment by boomzero** [comment]
你的issue怎么这么奇怪...

**Comment by boomzero** [comment]
a cosmetic change /user-script /priority-low

**Comment by PythonSmall-Q** [comment]
无可行判断依据/invalid

**Comment by boomzero** [comment]
@PythonSmall-Q Hendragon-bot?

**Comment by PythonSmall-Q** [comment]
这名字不错吧
