### ISSUE TITLE
[Feature Request] issue triage 后自动加入project

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#152]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by boomzero** [comment]
https://github.com/orgs/XMOJ-Script-dev/projects/2

**Comment by langningchen** [comment]
如果要这样，需要现将项目设为公有

**Comment by langningchen** [comment]
链接现在404

**Comment by langningchen** [comment]
![Screenshot_20231017_211854](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/b43e5dd7-92d1-4d7f-ba6d-2655c7f86821)

**Comment by PythonSmall-Q** [comment]
我来

**Comment by PythonSmall-Q** [comment]
共有了

**Comment by boomzero** [comment]
done!
