### ISSUE TITLE
[Bug] 站务版发帖检查

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#153]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![Screenshot_20231017_212444_Kiwi Browser](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/824c07ad-05f9-4c10-9492-e5f1de701157)

**Comment by boomzero** [comment]
很老的issue, 我以前做hash phpsessid时就有

**Comment by PythonSmall-Q** [comment]
嗯

**Comment by PythonSmall-Q** [comment]
主要是太忙

**Comment by PythonSmall-Q** [comment]
等一下，我怎么记得这玩意儿是检测的

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/master/Server/Source/Process.ts#L271
@langningchen

**Comment by PythonSmall-Q** [comment]
但是我尝试了一下，这句话一点都没用

**Comment by langningchen** [comment]
@PythonSmall-Q 你检查一下后台数据库

**Comment by langningchen** [comment]
表 bbs_board

**Comment by langningchen** [comment]
看一下是不是站务班的编号不是 0

**Comment by langningchen** [comment]
上面一行写了 `Data["BoardID"] === 0`

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/8120a99e-07e7-432f-b1d2-a3e4131a36d8)

**Comment by langningchen** [comment]
那你就逐行调试吧，我也不知道为什么

**Comment by langningchen** [comment]
打印中间变量来调试

**Comment by PythonSmall-Q** [comment]
Docs开始写了，你们帮个忙

**Comment by langningchen** [comment]
@PythonSmall-Q 我帮你？不可能 让 @boomzero 帮你吧

**Comment by boomzero** [comment]
@langningchen https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/3d13f3e1815dfa57145f941a379272640de176e9/Server/Source/Process.ts#L270

你~tm~调用函数不加括号的？（我调了一年……）

**Comment by boomzero** [comment]
fixed!

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-bbs/commit/ccc853b22c806c315b887b4a0fcdd623e61157ef#diff-9dc982bf412ba435f10cc40782fb368c23dfa18b6252ff0f15abcc6527d23d4f

**Comment by langningchen** [comment]
> 你~tm~调用函数不加括号的？（我调了一年……）

@boomzero 好吧

**Comment by langningchen** [comment]
我也真的服了，肯定是当时没有网络没有 Copilot ，不然肯定不会有这种低级错误

**Comment by langningchen** [comment]
而且都怪 JS 比较灵活，如果是 C++ 早就会报错了
