### ISSUE TITLE
[Bug] 统一截图长度

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#158]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

高度要保持一致，否则在官网的展示图片界面会一会儿长一会儿断

**Comment by PythonSmall-Q** [comment]
等我有空了改
