### ISSUE TITLE
[Bug] 状态界面“运行完成”不能成功处理

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#16]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/5150d8ae-cb5c-4238-b242-97f9f32cbc6e)

不能正常显示，导致后续执行失败

~轮到我来给你们提Issue 了~ 

### 重现步骤

~用 @PythonSmall-Q 的 PHPSESSID 登录进他的账号~

### 控制台错误信息

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'href')
```

**Comment by boomzero** [comment]
az, 6

**Comment by boomzero** [comment]
但是我没有她的phpsessid

**Comment by PythonSmall-Q** [comment]
az为啥我没发现（？？

**Comment by langningchen** [comment]
对啊，为啥我就发现了

**Comment by PythonSmall-Q** [comment]
哪个页面？

**Comment by langningchen** [comment]
@PythonSmall-Q 截图上面能看到URL

**Comment by PythonSmall-Q** [comment]
复现成功http://www.xmoj.tech/status.php?user_id=shanwenxiao&top=814186&prevtop=814920
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/0b735b5b-84a8-456e-a3bc-c2b20f895ace)

**Comment by PythonSmall-Q** [comment]
运行完成是什么东西啊

**Comment by langningchen** [comment]
你看看，你提交的PID是0，所以可能系统出 BUG 了

**Comment by PythonSmall-Q** [comment]
那这个东西就不fix了是xmoj的问题
又解决了一个issue喵呜

**Comment by PythonSmall-Q** [comment]
@langningchen 这个好像是“获取数据导致的”

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/40

**Comment by langningchen** [comment]
获取数据导致的？我这里获取数据没问题 

https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/40#issuecomment-1745964626

**Comment by boomzero** [comment]
应该和获取数据无关吧 /wontfix

**Comment by langningchen** [comment]
> 应该和获取数据无关吧

@boomzero 与获取数据有关

**Comment by boomzero** [comment]
How?

**Comment by langningchen** [comment]
就是 PID 生成写错了
