### ISSUE TITLE
[bug] 短消息可以发给不存在的用户

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#162]
![](https://api.xmoj-bbs.tech/GetImage?ImageID=mfmegiheotzetfjyttnvvhvonqktnjgp)

_Originally posted by @boomzero in https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/154#issuecomment-1772255519_

**Comment by boomzero** [comment]
@langningchen 你怎么做到的

**Comment by langningchen** [comment]
@boomzero shanwenxiao不是说过他把检测用户关了吗？

**Comment by langningchen** [comment]
另外，我对你随便乱翻数据库做出了强烈的谴责！ doge

**Comment by boomzero** [comment]
为什么关啊

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
> 另外，我对你随便乱翻数据库做出了强烈的谴责！ doge

我看一下

**Comment by langningchen** [comment]
你已经到家了？

**Comment by langningchen** [comment]
我还在学校，我要去打扫卫生了

**Comment by boomzero** [comment]
对

**Comment by langningchen** [comment]
好了

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/163 ...

**Comment by PythonSmall-Q** [comment]
检测用户使用我和学校里网关的问题

**Comment by langningchen** [comment]
> 检测用户使用我和学校里网关的问题

为什么？

**Comment by PythonSmall-Q** [comment]
我学校里的网关非常奇葩会ban

**Comment by boomzero** [comment]
不是啊, 这个是在服务器上发请求

**Comment by langningchen** [comment]
对啊

**Comment by langningchen** [comment]
@PythonSmall-Q 可能理解错了

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/e367396d-8001-49c2-87a6-641e50592d04)
开始更新

**Comment by PythonSmall-Q** [comment]
fixed
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/9526eaf5-a392-42c6-9387-56db3a2d9727)

**Comment by langningchen** [comment]
改了为什么不上传 GitHub?

**Comment by PythonSmall-Q** [comment]
啊还要上传github？？？

Sent from Mail for Windows

**Comment by PythonSmall-Q** [comment]
改了

Sent from Mail for Windows

**Comment by boomzero** [comment]
不传GitHub会导致你的更改被我覆盖(

**Comment by langningchen** [comment]
> 不传GitHub会导致你的更改被我覆盖(

@boomzero 说得对， @PythonSmall-Q 当然要上传啦
