### ISSUE TITLE
[Feature Request] 更新网址

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#166]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

Cloudflare Pages 可以直接在 `www.xmoj-bbs.tech` 上面显示了，而不是重定向到 `web.xmoj-bbs.tech`

**Comment by boomzero** [comment]
Backwards compatibility...

**Comment by PythonSmall-Q** [comment]
后向兼容

**Comment by langningchen** [comment]
但是你们为了向下兼容的版本也早就不能用了 @boomzero @PythonSmall-Q

**Comment by boomzero** [comment]
其实是的

**Comment by PythonSmall-Q** [comment]
确实，删了吧

**Comment by PythonSmall-Q** [comment]
fixed

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by langningchen** [comment]
好的

**Comment by langningchen** [comment]
@PythonSmall-Q 还是不行啊

**Comment by langningchen** [comment]
注意标题栏的地址
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/a5f1d529-2d69-486c-8c39-f860f0783a8d)

**Comment by langningchen** [comment]
左面访问不出来

**Comment by langningchen** [comment]
我说的是
```
Cloudflare Pages 可以直接在 www.xmoj-bbs.tech 上面显示了，而不是重定向到 web.xmoj-bbs.tech
```

**Comment by langningchen** [comment]
@PythonSmall-Q 但是现在还是把 www 重定向到了 web

**Comment by PythonSmall-Q** [comment]
我改了，你看看

**Comment by langningchen** [comment]
可以了
