### ISSUE TITLE
[Feature Request] 更换better预编译接口

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#167]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

更换更快的预编译api https://github.com/melpon/wandbox/blob/master/kennel/API.md

**Comment by langningchen** [comment]
我看看

**Comment by langningchen** [comment]
这个预编译一直都是大难题啊！

**Comment by PythonSmall-Q** [comment]
welcome测试

**Comment by PythonSmall-Q** [comment]
emm看了一下这个预编译比之前还要慢，/invalid
