### ISSUE TITLE
[Feature Request] 给用户脚本加图标

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#168]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

```js
// @icon ...
```

**Comment by PythonSmall-Q** [comment]
我看看

**Comment by PythonSmall-Q** [comment]
/-working-on-it
