### ISSUE TITLE
[Bug] 折叠无法显示

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#171]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

`https://www.xmoj-bbs.tech/` 的安装部分点击了 `联想浏览器` 也弹出的是 `Firefox`

**Comment by boomzero** [comment]
6 /website

**Comment by PythonSmall-Q** [comment]
哈》
