### ISSUE TITLE
[Bug] Autolabelissue 炸了

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#178]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/XMOJ-Script-dev/XMOJ-Script/actions/runs/6675876327

**Comment by langningchen** [comment]
这是因为你们用了 team 权限不一样，所以原来我才不用 team 一直用个人账户，就是为了避免权限问题

**Comment by PythonSmall-Q** [comment]
又空了看看

**Comment by PythonSmall-Q** [comment]
octokit的关系，等octokit更新

github修改了pr的api
/wontfix

**Comment by langningchen** [comment]
@PythonSmall-Q 你这也应该设置为 `/dependenies`

**Comment by boomzero** [comment]
不是

**Comment by boomzero** [comment]
github api 有`compatibility dates`

**Comment by boomzero** [comment]
fixed
