### ISSUE TITLE
[Feature Request] 增快讨论加载速度

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#18]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

增快讨论列表的加载速度，速度慢是因为过多的冗余 SQL 数据库查询

### 原因

太浪费时间

**Comment by boomzero** [comment]
@PythonSmall-Q @XMOJ-Script-dev/product-managers 快triage

**Comment by PythonSmall-Q** [comment]
很重要！！！！

**Comment by PythonSmall-Q** [comment]
~~emm您的历史遗留问题吧~~ @langningchen

**Comment by langningchen** [comment]
对的

**Comment by PythonSmall-Q** [comment]
嗯我觉得其实这个查找的逻辑没啥毛病以至于我找不到问题所在

**Comment by langningchen** [comment]
查找什么？

**Comment by langningchen** [comment]
主要消耗事件在服务器反复多余的 SQL 查询

**Comment by PythonSmall-Q** [comment]
用户本地存档（？

**Comment by PythonSmall-Q** [comment]
要不把UserName设置成一个礼拜（？

**Comment by langningchen** [comment]
真

**Comment by boomzero** [comment]
我让服务器把db放在east Asia, 然后他给我放到了美国西岸...

**Comment by boomzero** [comment]
@PythonSmall-Q 你能写一下吗

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 你们俩慢慢弄吧，我现在在忙着[这个](https://github.com/langningchen/FileShare)仓库

**Comment by PythonSmall-Q** [comment]
目前发帖、回复、短消息速度加快了qwq

**Comment by boomzero** [comment]
![](https://assets.xmoj-bbs.tech/GetImage?ImageID=mrtdxgvklwuetbfxjwrbqylngbmeahti)

done!

**Comment by boomzero** [comment]
我开了smart placement

**Comment by boomzero** [comment]
upd:

<img width="1376" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/ebe0215f-13aa-413e-91a0-16c90f83cb5c">

**Comment by PythonSmall-Q** [comment]
wow

**Comment by PythonSmall-Q** [comment]
Wow!

**Comment by langningchen** [comment]
@boomzero 🎉 👍 🥇 💯
