### ISSUE TITLE
[Feature Request] 增加公告功能

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#19]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

即使没有打开讨论功能的用户也可以看到全站公告，公告显示在首页

**Comment by PythonSmall-Q** [comment]
可以考虑一下

**Comment by PythonSmall-Q** [comment]
要不就站务版直接所有的链接都弄上来就行了吧qwq

**Comment by langningchen** [comment]
随便你吧

**Comment by langningchen** [comment]
反正这个项目也不是我改了

**Comment by langningchen** [comment]
或者还可以有功能：站务版自动提醒所有人

**Comment by langningchen** [comment]
这样效果和公告的差不多就一样了

**Comment by langningchen** [comment]
@PythonSmall-Q 你看你，不管你的 Issue ，都 stale 了

**Comment by boomzero** [comment]
@langningchen release notes? #303

**Comment by langningchen** [comment]
@boomzero 不是的

**Comment by langningchen** [comment]
@boomzero 类似于 AddonScript ，所有人强制弹出通知，但是长得很好看

**Comment by boomzero** [comment]
> @boomzero 类似于 AddonScript ，所有人强制弹出通知，但是长得很好看

well, You could just write addonscript using toast instead of alert, you know

**Comment by boomzero** [comment]
https://getbootstrap.com/docs/5.3/components/toasts/

**Comment by boomzero** [comment]
wtf?

**Comment by boomzero** [comment]
/-docs

**Comment by PythonSmall-Q** [comment]
> `https://getbootstrap.com/ docs/5.3/components/toasts/`

看上去不错，可以放到addonscript里面

**Comment by boomzero** [comment]
@langningchen added!

**Comment by boomzero** [comment]
meow

<img width="511" alt="image" src="https://github.com/user-attachments/assets/241cb5b4-0246-4741-b2a6-0df8467728e4">

**Comment by boomzero** [comment]
Can be edited using cloudflare kv
