### ISSUE TITLE
提案：domain transfer到cloudflare

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#191]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

domain transfer到cloudflare 功能更多，适配更好

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by PythonSmall-Q** [comment]
讨论一下orz

**Comment by langningchen** [comment]
我现在权限也没有了，也不负责开发了，这事我不管

**Comment by boomzero** [comment]
不行

**Comment by boomzero** [comment]
除非有人想付续费的钱

**Comment by boomzero** [comment]
但是,  现在dash炸了

**Comment by boomzero** [comment]
bug...

**Comment by boomzero** [comment]
@langningchen client transfer prohibited...

**Comment by boomzero** [comment]
unlock 一下

**Comment by PythonSmall-Q** [comment]
@boomzero 域名在我这里

**Comment by langningchen** [comment]
@boomzero 我已经把域名转让给了 @PythonSmall-Q
