### ISSUE TITLE
[Bug] 更新炸了

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#192]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

http://www.xmoj.tech/modifypage.php?ByUserScript=1没有东西，导致更新失败
问题根源：有小可爱加了cname，但是我不知道怎么关，谁来关一下

**Comment by PythonSmall-Q** [comment]
@boomzero @langningchen /priority-high

**Comment by langningchen** [comment]
![Screenshot_20231104_071701.jpg](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/a7b33ed0-01a7-4b29-a831-c16a500c4fa0)

？ @boomzero @PythonSmall-Q

**Comment by langningchen** [comment]
![Screenshot_20231104_071749.jpg](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/a51fd902-a9ce-42e5-9300-e730b0d86903)

**Comment by boomzero** [comment]
无法复现

**Comment by boomzero** [comment]
<img width="1920" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/94f4b61f-1146-4a9c-9a6c-9fc61fd10d7e">

**Comment by PythonSmall-Q** [comment]
![Uploading image.png…]()
我这里没东西

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/6c419cbd-aa29-4aa6-af18-7f3b50540598)

**Comment by PythonSmall-Q** [comment]
把cname关掉谢谢 @boomzero

**Comment by boomzero** [comment]
这和cname有什么关系...

**Comment by boomzero** [comment]
都要用<img width="1920" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/b876c358-537a-4602-8922-4e94e5bfd821">

**Comment by boomzero** [comment]
`* DNS Updates: Restored`

**Comment by PythonSmall-Q** [comment]
否则ghpages自动到cf

**Comment by langningchen** [comment]
？

**Comment by langningchen** [comment]
> 无法复现

我也感到很奇怪，我手机上和电脑上访问的不一样 @boomzero

**Comment by boomzero** [comment]
> 否则ghpages自动到cf

?

**Comment by boomzero** [comment]
哦

**Comment by boomzero** [comment]
我知道了

**Comment by boomzero** [comment]
@PythonSmall-Q https://blog.cloudflare.com/post-mortem-on-cloudflare-control-plane-and-analytics-outage/
