### ISSUE TITLE
[Bug] 开发者不认真

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#193]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

要在提交前测试，保证没有问题，先前的提交有很多都没测试，另外要好好理解理解服务器代码，防止改错

知道了以后就可以 close 了

**Comment by boomzero** [comment]
known, ~next~

**Comment by PythonSmall-Q** [comment]
known

**Comment by PythonSmall-Q** [comment]
明明是没来得及部署怎么就不认真了orz喵呜谁叫cf断电了

**Comment by langningchen** [comment]
> 明明是没来得及部署怎么就不认真了orz喵呜谁叫cf断电了

@PythonSmall-Q Emm...

**Comment by langningchen** [comment]
> known, ~next~

这个是个好主意 @boomzero
