### ISSUE TITLE
[Bug] XMOJ域名改了

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#194]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

改成了 yaoyao.xmoj.tech 而且支持 https 了？如果你直接访问 www.xmoj.tech 会导致证书不对

**Comment by boomzero** [comment]
?

**Comment by boomzero** [comment]
<img width="991" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/83981dbe-83ff-4f9f-8989-6bc1aa6f1d13">
...

**Comment by boomzero** [comment]
那个是redirect啊

**Comment by boomzero** [comment]
http...

**Comment by PythonSmall-Q** [comment]
dash最近不太稳定

**Comment by PythonSmall-Q** [comment]
不算问题，等高老师通知
/wontfix

**Comment by langningchen** [comment]
> http...

啊？我不太明白 @boomzero
