### ISSUE TITLE
[Feature Request] use worker secrets instead of secrets.ts

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#199]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://developers.cloudflare.com/workers/configuration/secrets

see https://github.com/langningchen/FileShare/issues/8

**Comment by langningchen** [comment]
:+1:

**Comment by PythonSmall-Q** [comment]
okay

**Comment by PythonSmall-Q** [comment]
什么玩意儿，没看懂怎么搞 /help-wanted /-investigating /working-on-it

**Comment by langningchen** [comment]
> 什么玩意儿，没看懂怎么搞

......

**Comment by PythonSmall-Q** [comment]
why???我觉得原来的挺好的

**Comment by PythonSmall-Q** [comment]
我把原来的弄得好一点

**Comment by boomzero** [comment]
安全。。。

**Comment by boomzero** [comment]
你这个相当于plaintext password

**Comment by langningchen** [comment]
@PythonSmall-Q 我赞同 @boomzero 说的

**Comment by boomzero** [comment]
done!
