### ISSUE TITLE
[Feature Request] 增加Badge的推广

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#20]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

只放一个接口进入打赏界面太少了，要增加推广，得到打赏后别忘分给我一点 😄

**Comment by PythonSmall-Q** [comment]
有接口吗（？？雾

**Comment by langningchen** [comment]
没有吗？

**Comment by PythonSmall-Q** [comment]
哪里（？？？

**Comment by PythonSmall-Q** [comment]
至少我记得当时没加过

**Comment by boomzero** [comment]
好问题

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/new/master?repository_funding=1

**Comment by PythonSmall-Q** [comment]
你写吧

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 推广方式也可以在 modifypage.php 显示标签修改并禁用，给出不能修改的原因和打赏链接

**Comment by PythonSmall-Q** [comment]
可以考虑

**Comment by PythonSmall-Q** [comment]
http://www.xmoj.tech/discuss3/thread.php?tid=223 打赏链接发了

**Comment by boomzero** [comment]
没有链接啊

**Comment by PythonSmall-Q** [comment]
是没有链接，看方法二

**Comment by langningchen** [comment]
@PythonSmall-Q 摆了是吧？

**Comment by langningchen** [comment]
我说的是要在修改个人设置#的时候也要显示 `badge 不可修改，请先打赏`

**Comment by PythonSmall-Q** [comment]
我在忙一模orz

> @PythonSmall-Q 摆了是吧？

**Comment by langningchen** [comment]
@PythonSmall-Q 我不知道这个网站

**Comment by langningchen** [comment]
Emm...

**Comment by langningchen** [comment]
@PythonSmall-Q 你看你，不管你的 Issue ，都 stale 了 /-stale

**Comment by langningchen** [comment]
哦，我没有权限使用 Actions 改标签……

**Comment by PythonSmall-Q** [comment]
awa我忙死了

**Comment by boomzero** [comment]
wtf is this issue doing?

**Comment by langningchen** [comment]
@boomzero 

> `只放一个接口进入打赏界面太少了，要增加推广，得到打赏后别忘分给我一点 😄`

**Comment by boomzero** [comment]
Well, https://opencollective.com/xmoj-script-development-froup
