### ISSUE TITLE
[Bug] release奇奇妙妙的错误

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#209]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/2a3a32b6-f157-46bd-bd3e-4c9e7e75cb32)

wtf》》》

**Comment by PythonSmall-Q** [comment]
为什么有两个1.0.239

**Comment by boomzero** [comment]
我弄的， 因为有奇怪的mergeconflict, 所以手动开了tag
