### ISSUE TITLE
[Feature Request] 帮助文档

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#210]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

使用mkdocs和actiong搭建帮助文档

**Comment by PythonSmall-Q** [comment]
new thing @boomzero @langningchen

**Comment by langningchen** [comment]
> new thing @boomzero @langningchen

@ 我 干啥...... 我现在已经是 No Code 模式了

**Comment by PythonSmall-Q** [comment]
err

**Comment by langningchen** [comment]
这个应该使用每个函数前面加注释，然后就可以直接生成文档了

**Comment by langningchen** [comment]
用 docgen 和 mkdocs

**Comment by PythonSmall-Q** [comment]
https://github.com/mhausenblas/mkdocs-deploy-gh-pages

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/docs 你们一起见一下 @langningchen @boomzero
