### ISSUE TITLE
[Feature Request] 前后端使用不同仓库

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#228]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by langningchen** [comment]
为什么？

**Comment by langningchen** [comment]
不过也可以

**Comment by PythonSmall-Q** [comment]
嗯

**Comment by PythonSmall-Q** [comment]
你建吧

**Comment by boomzero** [comment]
done
