### ISSUE TITLE
[Feature Request] 增加姓名

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#23]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

通过腾讯会议会议昵称增加姓名列表的内容，并且在除了 ACM 排名的其他界面也显示姓名

**Comment by PythonSmall-Q** [comment]
可以考虑一下

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by langningchen** [comment]
@PythonSmall-Q 以后那个 Devepolment 也把 PR Link上
