### ISSUE TITLE
[Bug]帮我看看旧版切换

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#24]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

帮我看看旧版切换，没办法从Pythonsmall-Q更新到xmoj-script-dev

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by boomzero** [comment]
等一下吧

**Comment by boomzero** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/3bf8039b-a6b1-4805-90d2-d286e5bb29e1)
6...

**Comment by boomzero** [comment]
说明我read了4400条消息

**Comment by boomzero** [comment]
@PythonSmall-Q ~你好像把服务器ddos了~

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/a1b09a36-3aa6-4511-aa13-d8ed3402d0ba)

**Comment by PythonSmall-Q** [comment]
王炸

**Comment by PythonSmall-Q** [comment]
解决方案：master同步到pythonsmall-q下面的master分支，开发者用xmoj的新的

**Comment by PythonSmall-Q** [comment]
如果切换失败只能换成PythonSmall-Q的仓库， @boomzero 你看看能行吗

**Comment by boomzero** [comment]
不要急, 我在写作业

**Comment by boomzero** [comment]
@PythonSmall-Q 我突然发现我在做你们学校去年的月考卷

**Comment by boomzero** [comment]
@XMOJ-Script-dev/product-managers https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/33#issuecomment-1744621716

**Comment by PythonSmall-Q** [comment]
> @PythonSmall-Q 我突然发现我在做你们学校去年的月考卷

66666

**Comment by PythonSmall-Q** [comment]
fixed

**Comment by PythonSmall-Q** [comment]
/-investigating
