### ISSUE TITLE
[Feature Request] write a parser for cph

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#246]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/agrawal-d/cph

**Comment by boomzero** [comment]
However, I do not use cph

**Comment by boomzero** [comment]
because I use Clion

**Comment by PythonSmall-Q** [comment]
What the f is cph

**Comment by langningchen** [comment]
@PythonSmall-Q 请使用BDFS算法 (BaiDu First Search 百度优先搜索算法)

**Comment by PythonSmall-Q** [comment]
why not planned？？？

**Comment by boomzero** [comment]
Umm, stale?

**Comment by PythonSmall-Q** [comment]
i think that cph doesn't support other websites except those supported by competive companion and cph itself, so why should we do it ovo @boomzero  /questions

**Comment by boomzero** [comment]
We(you) should do it

**Comment by PythonSmall-Q** [comment]
那你给cph发pr呗

**Comment by boomzero** [comment]
> 那你给cph发pr呗

不是cph管的 @PythonSmall-Q

**Comment by boomzero** [comment]
其实是https://github.com/jmerle/competitive-companion#readme

**Comment by boomzero** [comment]
但是OJTool实现了, 所以不考虑

**Comment by boomzero** [comment]
@langningchen 的OJTool
