### ISSUE TITLE
[Feature Request] set up all labels

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#25]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

有些label没有

**Comment by PythonSmall-Q** [comment]
@boomzero 你link一下PR

**Comment by PythonSmall-Q** [comment]
这样我知道在做了

**Comment by PythonSmall-Q** [comment]
fixed/-investigating /-working-on-it

**Comment by boomzero** [comment]
这不用pr
