### ISSUE TITLE
[Bug] UpdateToRelease无限递归

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#266]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/251

**Comment by boomzero** [comment]
<img width="1367" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/70caddd6-c759-4a41-bd5f-01be306f893e">
...

**Comment by PythonSmall-Q** [comment]
艹

**Comment by boomzero** [comment]
解决方法：去掉app
