### ISSUE TITLE
[Bug] 更新日志

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#275]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

能否好好的改改先前的更新日志？

**Comment by langningchen** [comment]
@PythonSmall-Q 你看看，就最后一次正式发布的更新日志

分别是
- Update Prerelease.yml
- 烦死了。。。
- Update Prerelease.yml
- wtf
- 使用Base64编码icon
- 发送统计数据

就最后两个有用，前面四个都是什么日志，这拿出去难道不会被人笑话吗？

~@boomzero 你来说说我说的是不是很对 Doge~

https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/fc039e7e9367275cbeb75bcc6a6bed39fac5249c/Update.json#L569-L598

**Comment by boomzero** [comment]
Emm，这都是改GitHub apps时干的，当时我要疯了

**Comment by boomzero** [comment]
@langningchen 有了这个功能，这个issue就不会有了（

<img width="1303" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/5e7ab28b-73a7-4404-aaff-fe1a0491cc9a">

**Comment by PythonSmall-Q** [comment]
wow！！！

**Comment by PythonSmall-Q** [comment]
所以这玩意儿可以结了？？
