### ISSUE TITLE
[Bug] 适配https

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#277]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

小明改为https，先前许多功能需要适配

**Comment by langningchen** [comment]
需要 Bump Version

**Comment by boomzero** [comment]
@langningchen @PythonSmall-Q 没有啊 
<img width="1386" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/ba8a0882-7c19-4bc9-b0e4-33306d642d5c">

**Comment by langningchen** [comment]
> @langningchen @PythonSmall-Q 没有啊 <img alt="image" width="1386" src="https://private-user-images.githubusercontent.com/85378277/287282992-ba8a0882-7c19-4bc9-b0e4-33306d642d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NzkwODEsIm5iZiI6MTcwMTQ3ODc4MSwicGF0aCI6Ii84NTM3ODI3Ny8yODcyODI5OTItYmE4YTA4ODItN2MxOS00YmM5LWIwZTQtMzMzMDZkNjQyZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDAwNTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YjViYWRhMmRmNTM4NzQ2N2M4ZGNkNjZiNGE3N2YwMzdlMDBjOTNkYzAzNzJmNDJmNDNmZGUyNmJhNmFiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.drggQU4V7tSVBYdFkJbKvrbpFLepIhHEev08KmCo7kk">

你手动在http后面加一个s

**Comment by boomzero** [comment]
fixed, please test @langningchen @PythonSmall-Q
