### ISSUE TITLE
[Feature Request] 使用dependabot扫描依赖

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#285]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

它可以自动扫描submodel的更新并提出PR

### 原因

每次都sync back太麻烦

**Comment by PythonSmall-Q** [comment]
areyousure dependabot能建submodule？？？ @langningchen  how about you @boomzero

**Comment by langningchen** [comment]
@PythonSmall-Q 他是能 scan submodule ，而不是建立

**Comment by langningchen** [comment]
等到下周一模考完以后就快点干活，或者把这个actions删了
