### ISSUE TITLE
[Bug] 无法在某些页面检查登录状态

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#286]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

比如短消息页面 `mail.php` ，无法自动跳转到登录界面

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/1f821be9-f509-4f59-b3f5-b0298ce3a074)
有的呀

**Comment by PythonSmall-Q** [comment]
但是没有人会直接访问mail呀你不登陆都没有popup

**Comment by langningchen** [comment]
> 还是说你说的是自动跳到登录页面？

对的

**Comment by boomzero** [comment]
fixed @langningchen

**Comment by boomzero** [comment]
Regression..?

**Comment by boomzero** [comment]
Caused by #804

**Comment by boomzero** [comment]
Fixed again @langningchen (

**Comment by langningchen** [comment]
👍
