### ISSUE TITLE
[Feature Request] 比赛结束后自动在题目下提交

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#287]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt, 而不是显示提交失败

### 原因

<img width="1854" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/10492fab-8c9a-449a-8a45-d2947e7a3da4">

**Comment by PythonSmall-Q** [comment]
我们还是要遵守用户干涉么我们执行什么

**Comment by boomzero** [comment]
现在unknown error

**Comment by boomzero** [comment]
I will copy qsm's implementation

**Comment by boomzero** [comment]
Yay!!! Finally fixed! 🎉
