### ISSUE TITLE
[Feature Request] 使用 GM 存储信息

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#296]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

使用 GM 系列函数，而不是 localstorage

**注意需要使用 AddonScript 或者其他方法将用户端的 localstorage 存储全部转移到 GM**

### 原因

GM 存储的内容只要开启了 sync 功能就能跨浏览器同步，但是 localstorage 不行

**Comment by PythonSmall-Q** [comment]
好东西

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> 
> 
> ### 描述
> 
> 使用 GM 系列函数，而不是 localstorage
> 
> **注意需要使用 AddonScript 或者其他方法将用户端的 localstorage 存储全部转移到 GM**
> ### 原因
> 
> GM 存储的内容只要开启了 sync 功能就能跨浏览器同步，但是 localstorage 不行

其实是跨域名同步，而不是跨浏览器同步，因此没用

**Comment by langningchen** [comment]
@boomzero 你确定吗？我看他说的是跨浏览器同步

**Comment by boomzero** [comment]
> @boomzero 你确定吗？我看他说的是跨浏览器同步

Where

**Comment by langningchen** [comment]
> > @boomzero 你确定吗？我看他说的是跨浏览器同步
> 
> Where

我得明天开电脑看一看

**Comment by langningchen** [comment]
好像我确实看错了 /invalid
