### ISSUE TITLE
[Feature Request] ACM 排名界面增加动画与名次历史

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#30]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

增加上下排位动画，并且画出排名历史的折线图

**Comment by PythonSmall-Q** [comment]
wc有点东西

**Comment by langningchen** [comment]
这个是我很早的思路，后来突然忘记做了

**Comment by PythonSmall-Q** [comment]
我觉得langningchen在转手之后活跃了不少

**Comment by langningchen** [comment]
@PythonSmall-Q 这是应为我把我的所有思路都提出成为了 Issue ，本来我准备直接修掉，不写 Issue

**Comment by boomzero** [comment]
this is hard..

**Comment by langningchen** [comment]
@boomzero 没有很难啊

**Comment by langningchen** [comment]
~可能因为我太强了~

**Comment by boomzero** [comment]
因为我不知道你要什么, can you clarify?

**Comment by boomzero** [comment]
怎么来的动画?

**Comment by boomzero** [comment]
根据以前的比赛?

**Comment by langningchen** [comment]
我弄简单一点，就是画一张折线图表示在当前比赛中你的名词的变化情况
