### ISSUE TITLE
[Feature Request] 改进自动标签处理

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#31]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

~~- [ ] 当分支创建时连接分支到 Issue~~
- [x] #85
- [x] #84
- [x] #83

**Comment by boomzero** [comment]
@langningchen  当分支创建时连接分支到 Issue 是什么意思

**Comment by langningchen** [comment]
如果有一个 branch 创建了，根据 branch 的名字提取出 IssueID ，然后在对应的 Issue 的 Development 连接这个 branch

**Comment by boomzero** [comment]
> 如果有一个 branch 创建了，根据 branch 的名字提取出 IssueID ，然后在对应的 Issue 的 Development 连接这个 branch

没有必要吧

**Comment by boomzero** [comment]
毕竟有closing keyword

**Comment by langningchen** [comment]
随便你们

**Comment by langningchen** [comment]
不过即使加了我也用不到了 😄

**Comment by PythonSmall-Q** [comment]
@boomzero 所以这个你来做对吧
