### ISSUE TITLE
[Bug] 免费域名 `eu.org` 会被封

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#32]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

应当切换为 `xmoj-bbs.tech`

**Comment by PythonSmall-Q** [comment]
@boomzero 你来吧这个方便

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。
> 
> 
> ### 描述
> 
> 应当切换为 `xmoj-bbs.tech`
> ### 重现步骤
> 
> _No response_
> ### 控制台错误信息
> 
> _No response_

已经切换了, 在dev上

**Comment by langningchen** [comment]
好的
