### ISSUE TITLE
[Feature Request] 封禁用户

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#326]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

功能描述：允许管理团队和运维团队永久、暂时禁止用户发言、发短消息、上传图片等限制措施

anyways, we will add a d1 table that marks what functions a user is allowed to call

**Comment by boomzero** [comment]
Well, I suppose you want a GUI

**Comment by PythonSmall-Q** [comment]
yep

**Comment by boomzero** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/0e682aab-2f5b-4bd0-99ec-113f0fb47050)

**Comment by PythonSmall-Q** [comment]
？？啥意思

**Comment by shihongxi** [comment]
这个功能现在做好了吗？

**Comment by langningchen** [comment]
没有UI你们自己写呀

**Comment by PythonSmall-Q** [comment]
感觉好像这玩意儿就可以cover刚刚那个举报功能

**Comment by PythonSmall-Q** [comment]
gui要不就不要了？我们直接写deploy @boomzero

**Comment by PythonSmall-Q** [comment]
@boomzero  
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/a9076b6f-dc5b-4e7f-aa93-bf5cc97aeb90)
考完道法脑子坏了

**Comment by boomzero** [comment]
@PythonSmall-Q 
<img width="1920" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/050448b1-36c3-4216-8e30-795c4e4bd56b">

**Comment by PythonSmall-Q** [comment]
《独裁》的PM蒻篛的问一句好了吗（我封人急不可耐了

**Comment by boomzero** [comment]
封谁?

**Comment by PythonSmall-Q** [comment]
就想玩玩封封自己

**Comment by boomzero** [comment]
如你所愿

**Comment by PythonSmall-Q** [comment]
c 
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/cfc7fcd8-9352-4a37-85c3-867211bd2198)

ntmlgbd 封我干嘛nmsl

**Comment by boomzero** [comment]
> 如你所愿

> c ![image](https://private-user-images.githubusercontent.com/106425289/301145045-cfc7fcd8-9352-4a37-85c3-867211bd2198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQwNTUsIm5iZiI6MTcwNjcwMzc1NSwicGF0aCI6Ii8xMDY0MjUyODkvMzAxMTQ1MDQ1LWNmYzdmY2Q4LTkzNTItNGEzNy04NWMzLTg2NzIxMWJkMjE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMjIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2NiMDFmMDEzMDAxOTE3NjkzNmYyOWIyZTAzNjU5MDExZTljZDJmM2E2Y2VkYTgxNmEyNmFlMmU0OWNiZWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tUP3dtFomWqzUt0EtwmK_sr798G1MJ_Qqu00Pal_JPw)
> 
> ntmlgbd 封我干嘛nmsl

~cute swx 不要骂人~

**Comment by boomzero** [comment]
<img width="1611" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/5eff8269-f20d-4424-8805-f2983d5f8e4c">

**Comment by PythonSmall-Q** [comment]
……

**Comment by PythonSmall-Q** [comment]
啊不是还没好吗？

**Comment by boomzero** [comment]
目前没什么用, 等用户多了再说吧
