### ISSUE TITLE
[Feature Request] 确认仓库 

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#33]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

如果 https://github.com/PythonSmall-Q/XMOJ-Script 不被使用就设立向这个仓库的链接，将代码中的链接改好，然后 Archive 或删除那个仓库

**Comment by PythonSmall-Q** [comment]
我改的时候遇到了一些问题，你要不一起修改一下？？？

**Comment by langningchen** [comment]
有什么问题？

**Comment by langningchen** [comment]
我现在只是一个技术顾问了，不再参与开发活动

**Comment by langningchen** [comment]
有什么问题可以问我

**Comment by langningchen** [comment]
#39

**Comment by boomzero** [comment]
需要把pages转到这个仓库上

我不是团队admin,所以改不了

**Comment by boomzero** [comment]
@XMOJ-Script-dev/product-managers

**Comment by PythonSmall-Q** [comment]
我转了呀~

**Comment by PythonSmall-Q** [comment]
等一下，再转了

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/af8c0727-f2e2-499a-a871-f1b13fb25cc9)
域名不变

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by PythonSmall-Q** [comment]
之前的能成功转了

**Comment by boomzero** [comment]
thx

**Comment by boomzero** [comment]
那就好了?
