### ISSUE TITLE
[Bug] 题解标题显示

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#332]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="1345" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/5df95b04-717c-4a95-8ac0-76b7d3e1d338">

提示：
其实原因一样，fix也很简单

**Comment by PythonSmall-Q** [comment]
哦知道了

**Comment by PythonSmall-Q** [comment]
误操作了

**Comment by boomzero** [comment]
I will do this
