### ISSUE TITLE
[Feature Request] 备案网站

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#337]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/e882e91a-1b80-40a5-9c0e-dded204343b6)

目前备案在审核，如果审核不过的话要重新修改

备案验证链接：https://icp.gov.moe/?keyword=20240425

**Comment by langningchen** [comment]
萌备还要审核啊，我原来备案都是秒过，而且还挑自己喜欢的备案号

**Comment by langningchen** [comment]
开始我看到标题吓一跳，还以为你要真的备案，后来才发现是萌备 🤣

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/32115656-7676-4333-9681-99d9dd74ece4)
审核过啦！

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/87ba6edc-c63e-4912-93b2-6bc3dbbff54e)
