### ISSUE TITLE
[Feature Request] 增加 Milestone

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#34]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

不然 AutoLabel.js 无法发挥出她最大的性能

**Comment by PythonSmall-Q** [comment]
《她》

**Comment by langningchen** [comment]
Emm 我也不知道

**Comment by boomzero** [comment]
done

**Comment by PythonSmall-Q** [comment]
/-investigating
