### ISSUE TITLE
[Bug] What did cln do?

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#341]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="573" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/15bb1ad3-4247-4386-af9c-bba78b3b2385">
@langningchen 你是怎么把你的用户名删掉的

**Comment by langningchen** [comment]
@boomzero ？

**Comment by langningchen** [comment]
什么意思？还有为什么这是BUG？ ...

**Comment by boomzero** [comment]
意思是, 你为什么不在contributors 里

**Comment by langningchen** [comment]
@boomzero 不知道

**Comment by PythonSmall-Q** [comment]
我也想知道orz

**Comment by boomzero** [comment]
> @boomzero 不知道

你问一下github support?

**Comment by langningchen** [comment]
@boomzero 不用

**Comment by PythonSmall-Q** [comment]
Repen干嘛

**Comment by PythonSmall-Q** [comment]
不是，这玩意儿时github的事情和我们没关系啊

**Comment by boomzero** [comment]
Emm

**Comment by boomzero** [comment]
I think this is a config bug on our side
