### ISSUE TITLE
[Bug] `Toggle navigation` button appears and disappears

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#342]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="1651" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/8a35ab56-f9a7-4a6c-b86b-5a73f21f7632">

### 重现步骤

visit https://www.xmoj.tech/contest.php

### 控制台错误信息

N/A

**Comment by langningchen** [comment]
Nothing wrong

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/4e3d65c0-5cd7-43f2-8780-6e085d9c3ef9)

**Comment by PythonSmall-Q** [comment]
nothing wrong either？？

**Comment by boomzero** [comment]
Use Firefox

**Comment by boomzero** [comment]
[Firefox 2024-01-12 11.57 profile.json.gz](https://github.com/XMOJ-Script-dev/XMOJ-Script/files/13912035/Firefox.2024-01-12.11.57.profile.json.gz)

Here is a debugging profile

**Comment by boomzero** [comment]
Here is a gui, so you don't have to look at json:

https://profiler.firefox.com/from-url/https%3A%2F%2Fgithub.com%2FXMOJ-Script-dev%2FXMOJ-Script%2Ffiles%2F13912035%2FFirefox.2024-01-12.11.57.profile.json.gz/calltree/?v=10

**Comment by boomzero** [comment]
Well, as you can see here, it is present in the html

<img width="1661" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/ea1616b8-d0be-497a-b51b-f223f4b4b907">

**Comment by boomzero** [comment]
Also for some reason I am loading two versions of bootstrap

**Comment by langningchen** [comment]
我没有 Firefox

**Comment by PythonSmall-Q** [comment]
我的firefox没问题啊

**Comment by PythonSmall-Q** [comment]
load的时候肯定会有toogle navigation的

**Comment by boomzero** [comment]
Oh, so this is normal, but still very annoying

**Comment by langningchen** [comment]
两个bootstrap之间切换，总归会出很奇怪的问题，比如 #343 也是

**Comment by boomzero** [comment]
small upd: 
```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable

**Comment by boomzero** [comment]
This is the latest version of firefox I built myself, so

**Comment by boomzero** [comment]
@PythonSmall-Q Hello, I apologize for bringing up what may seem like a trivial issue, but I believe it could be resolved by manually removing the button in the script.

**Comment by boomzero** [comment]
/-invalid /bug /userscript

**Comment by PythonSmall-Q** [comment]
啊？又咋啦？
