### ISSUE TITLE
[Feature Request] 一个新的骗数据法

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#345]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

我发现, xmoj 会把 stderr 上的内容展示出来, 无论是否RE, 所以只需把数据`clog`出来就行了

**Comment by langningchen** [comment]
没明白

**Comment by boomzero** [comment]
<img width="1798" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/beb961a3-6a7b-4b63-85a7-5a5e811af9f1">

**Comment by boomzero** [comment]
<img width="1798" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/7d043080-cf9f-4832-bc4a-4ef63fefbe0e">

**Comment by langningchen** [comment]
哦，真棒

**Comment by langningchen** [comment]
这样应该就没有最大长度限制了

**Comment by PythonSmall-Q** [comment]
好主意，但为什么要assign我

**Comment by boomzero** [comment]
duplicate of #40
