### ISSUE TITLE
[Feature Request] 数据点被审批后向用户发送通知

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#347]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

**Comment by PythonSmall-Q** [comment]
啊？这好像检测不了的

**Comment by boomzero** [comment]
Crawl

**Comment by langningchen** [comment]
爬虫是不是感太耗服务器资源了？

**Comment by boomzero** [comment]
> 爬虫是不是太耗服务器资源了？

在client side 爬

**Comment by boomzero** [comment]
就是, 用户可以选择watch 一个page, 然后script 存到localstorage里

**Comment by langningchen** [comment]
我是说太耗高老师服务器的资源了

**Comment by boomzero** [comment]
> 我是说太耗高老师服务器的资源了

~没事, 你看我天天干什么~

<img width="682" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/f31fad8f-9652-4a00-9d67-77d1133510fc">

**Comment by boomzero** [comment]
<img width="682" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/d9c2b3b5-6b2d-442c-a602-4990e06eb37d">

**Comment by langningchen** [comment]
好好好

**Comment by boomzero** [comment]
?

**Comment by PythonSmall-Q** [comment]
/-invalid /enhancement /investigating /frozen

**Comment by PythonSmall-Q** [comment]
太耗费资源了，做人要留一线喵

**Comment by boomzero** [comment]
No!

**Comment by PythonSmall-Q** [comment]
向高老师推销xmoj，他说不装但我看到了admin，基础是bootstrap5.2.2

**Comment by langningchen** [comment]
你推销 XMOJ ？还是 XMOJ-Script ？ @PythonSmall-Q

**Comment by langningchen** [comment]
这个功能可以在 XMOJ-Client 中实现，我提前预留接口了

**Comment by PythonSmall-Q** [comment]
script

**Comment by langningchen** [comment]
> script

?

**Comment by langningchen** [comment]
现在 XMOJ 是什么情况？

**Comment by boomzero** [comment]
?

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/e7cad7ee-5767-45bf-9a48-6b43a5f14a24" />

**Comment by boomzero** [comment]
> 就是说这一道题第一次申请自动审批

Cannot reproduce

**Comment by PythonSmall-Q** [comment]
现在都是自动审批了

**Comment by boomzero** [comment]
Wow
