### ISSUE TITLE
[Bug] 更改错误的板块

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#35]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

将先前有关题目的讨论换到题目总版，202号讨论改为反馈区

**Comment by PythonSmall-Q** [comment]
有点累欸

**Comment by PythonSmall-Q** [comment]
《摆》/priority-low

**Comment by PythonSmall-Q** [comment]
@langningchen 我觉得之前的就没必要改了，很多都很水

**Comment by PythonSmall-Q** [comment]
202我去改以一下

**Comment by PythonSmall-Q** [comment]
202fixed，现在202是反馈版了

**Comment by langningchen** [comment]
好吧

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by PythonSmall-Q** [comment]
/-working-on-it
