### ISSUE TITLE
[Feature Request] 举报系统

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#354]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

对于具有侮辱性的内容，用户可以举报该用户。管理员在管理板块可以删除对应的内容（管理板块可以用https://www.xmoj.tech/admin/ 直接魔改

### 原因

政策对应：《中华人民共和国未成年人网络保护条例》

> 第二十九条　网络产品和服务提供者应当加强对用户发布信息的管理，采取有效措施防止制作、复制、发布、传播违反本条例第二十二条、第二十四条、第二十五条、第二十六条第一款、第二十七条规定的信息，发现违反上述条款规定的信息的，应当立即停止传输相关信息，采取删除、屏蔽、断开链接等处置措施，防止信息扩散，保存有关记录，向网信、公安等部门报告，并对制作、复制、发布、传播上述信息的用户采取警示、限制功能、暂停服务、关闭账号等处置措施。 网络产品和服务提供者发现用户发布、传播本条例第二十三条第一款规定的信息未予显著提示的，应当作出提示或者通知用户予以提示；未作出提示的，不得传输该信息。

@langningchen @boomzero 主要是防止有**举报然后我还得吃官司

**Comment by boomzero** [comment]
stop...

**Comment by PythonSmall-Q** [comment]
爱咋啦

**Comment by PythonSmall-Q** [comment]
那段消息总有人用的吧

**Comment by boomzero** [comment]
> 那段消息总有人用的吧

wait

**Comment by PythonSmall-Q** [comment]
算了算了，不搞就不搞了

**Comment by boomzero** [comment]
@PythonSmall-Q thx

**Comment by PythonSmall-Q** [comment]
（设想的新功能又没了

**Comment by boomzero** [comment]
anyways
