### ISSUE TITLE
[Bug] 过长的Badge显示效果不佳

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#36]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/8871e7db-0d93-4626-9903-4cf807659c45)

Badge 过长时会换行显示，应当保持在同一行

**Comment by PythonSmall-Q** [comment]
这个我觉得换行看上去是不是更简洁了捏

**Comment by langningchen** [comment]
是吗？我没有觉得

**Comment by PythonSmall-Q** [comment]
同一行的话半屏会看着非常难受，个人认为不改了吧 /wontfix

**Comment by langningchen** [comment]
好的
