### ISSUE TITLE
[Bug] 脚本存在代码语法问题（1330:20）await不位于async外

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#364]
### 描述

tampermonkey allows this, but other userscript managers don't

> Code contains errors: Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules at undefined:508:12

> Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules at undefined:1330:20

**Comment by PythonSmall-Q** [comment]
对的，我昨天在发送greasefork的时候也发现了

**Comment by PythonSmall-Q** [comment]
script-cat跑不了这个

**Comment by PythonSmall-Q** [comment]
@boomzero https://github.com/XMOJ-Script-dev/XMOJ-Script/raw/master/XMOJ.user.js - Codecontains errors: Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules at undefined:1330:20

**Comment by boomzero** [comment]
@PythonSmall-Q 
https://greasyfork.org/en/scripts/486112

**Comment by PythonSmall-Q** [comment]
boomzero好棒
