### ISSUE TITLE
[Feature Request] 讨论列表增加显示数量

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#37]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

改为每页显示 20 个

**Comment by PythonSmall-Q** [comment]
那这样的话加载时间就会很长

**Comment by langningchen** [comment]
所以要先解决 #18

**Comment by PythonSmall-Q** [comment]
working-ob-it，由于cf的degradedperformance，目前部署存在困难

**Comment by PythonSmall-Q** [comment]
```
Line 18117 & 18118: 10->20
```

**Comment by PythonSmall-Q** [comment]
/-frozen

**Comment by langningchen** [comment]
现在这个还是不行

**Comment by PythonSmall-Q** [comment]
部署好了

**Comment by PythonSmall-Q** [comment]
@langningchen 现在可以了

**Comment by langningchen** [comment]
好的
