### ISSUE TITLE
[Bug]获取标程失败

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#379]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/94766918/36aa3428-641d-48e3-8e85-1960387bc989)

**Comment by PythonSmall-Q** [comment]
您好，我们已收到您的反馈。这边建议您在遇到这种问题时先尝试刷新页面重新上传。如果问题重现，请复制控制台错误信息（如果有）并在此告诉我们，谢谢。

PS：如果问题确实存在，请及时反馈给我们（issue有效周期7天，开发组接到bug修复周期14个工作日）

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/5e50fc46-842f-4005-ba48-4400a7a4d4d2)
我这边正常的

**Comment by boomzero** [comment]
hmm, let me try

**Comment by boomzero** [comment]
请重试

如果问题仍不能解决, 请提供更多信息(访问URL等)

**Comment by zhouyiqing0304** [comment]
1 此题还没有人上传标程

**Comment by zhouyiqing0304** [comment]
怎么办

**Comment by PythonSmall-Q** [comment]
emm这说明除了你还没有任何xmoj-script用户答对了这道题。顺便问一声，那道题啊发给链接呗我看看我对没对

**Comment by PythonSmall-Q** [comment]
> 1 此题还没有人上传标程

对于您的这个问题，https://github.com/XMOJ-Script-dev/XMOJ-bbs/issues/10 解决后将会出现的频次少一些
