### ISSUE TITLE
[Bug] 状态页面显示歪斜（运行完成导致）

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#392]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="1675" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/f2e5994f-ea1a-49b3-aa32-be95d0f9c26c">

**Comment by PythonSmall-Q** [comment]
？？？

**Comment by PythonSmall-Q** [comment]
欸不对呀为什么会有0的

**Comment by boomzero** [comment]
自动获取数据

**Comment by boomzero** [comment]
@PythonSmall-Q 但是这是hustoj的bug吧, report 一下?

**Comment by langningchen** [comment]
不是的 hustoj 的，但是尽管是，最新版也可能依旧修复好了

**Comment by boomzero** [comment]
@langningchen 你convince 高老师更新一下hustoj, 再convince他改一下theme, xmoj-script就可以不要了

**Comment by boomzero** [comment]
@langningchen wtf are you thinking?

<img width="734" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/0cda121f-4664-49c9-a443-de7d0c16a311">

**Comment by langningchen** [comment]
不过有什么问题吗？

**Comment by langningchen** [comment]
这行代码看起来没用，不过实际上是有用的。

**Comment by langningchen** [comment]
他能将一个HTML去除格式，只保留里面的文字

**Comment by PythonSmall-Q** [comment]
我问过，他说更新不了，因为改动太多了，否则白改了

**Comment by boomzero** [comment]
我知道为什么, ***@***.***的锅

因为pid是null

**Comment by boomzero** [comment]
因为 @langningchen 获取pid 的方式是去localstorage中找
如果找不到就是null

**Comment by langningchen** [comment]
确实

**Comment by boomzero** [comment]
After https://github.com/XMOJ-Script-dev/XMOJ-Script/commit/fdc4601ca151630c6db47155279e1ff276d787e4 , This won't happen again.
