### ISSUE TITLE
[Bug] 更改获取数据体验

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#40]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

获取不到数据时应当提示，而不是卡住

**Comment by PythonSmall-Q** [comment]
历史遗留问题

**Comment by PythonSmall-Q** [comment]
@langningchen 你要不像个解决思路

**Comment by langningchen** [comment]
我有

**Comment by langningchen** [comment]
不过你也要自己想一个

**Comment by PythonSmall-Q** [comment]
@langningchen

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/16

**Comment by PythonSmall-Q** [comment]
喵呜，能两个一起解决了

**Comment by PythonSmall-Q** [comment]
（我想删掉获取数据
因为他不稳定

**Comment by PythonSmall-Q** [comment]
我尝试了6次获取数据没有一次是成功的

**Comment by PythonSmall-Q** [comment]
emm我其实很想把这个功能移除掉（首先这玩意儿拉低正确率，其次是某天gls问我提交这东西干嘛

**Comment by langningchen** [comment]
@PythonSmall-Q 我昨天就用到了

**Comment by langningchen** [comment]
觉得还挺好用

**Comment by langningchen** [comment]
你可以设置一个开关，允许关闭这个功能

**Comment by PythonSmall-Q** [comment]
好的。默认关闭（doge

**Comment by PythonSmall-Q** [comment]
《我可是最友善的管理》

**Comment by langningchen** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/ef218cbc-f01c-4951-b5e2-28704cf381db

**Comment by PythonSmall-Q** [comment]
> xxhcu-lwpyr.mp4

但是这个东西不稳定。我尝试了好几次都失败了

**Comment by langningchen** [comment]
失败因为样例太大了

**Comment by langningchen** [comment]
传不回来

**Comment by PythonSmall-Q** [comment]
……

**Comment by langningchen** [comment]
就是样例太长了，被系统自动裁掉了，因为我是通过标准错误流传输数据的，而标准错误流回传有最大的长度限制

**Comment by PythonSmall-Q** [comment]
err

**Comment by langningchen** [comment]
有的像这种太长了，所以就获取不到了

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/632d22b7-d035-4973-9c9d-273bcb391856)

**Comment by langningchen** [comment]
但是我们可以观察到这些数据很多都是重复的，所以可以增加压缩算法，使得能传回来更多数据

**Comment by PythonSmall-Q** [comment]
先搞开关，急吼吼发布学术模式

**Comment by boomzero** [comment]
> emm我其实很想把这个功能移除掉（首先这玩意儿拉低正确率，其次是某天gls问我提交这东西干嘛

no

**Comment by boomzero** [comment]
> 但是我们可以观察到这些数据很多都是重复的，所以可以增加压缩算法，使得能传回来更多数据

其实base64有点浪费

**Comment by boomzero** [comment]
zstd?

**Comment by langningchen** [comment]
> > 但是我们可以观察到这些数据很多都是重复的，所以可以增加压缩算法，使得能传回来更多数据
> 
> 其实base64有点浪费

@boomzero 确实

**Comment by boomzero** [comment]
但是Ztsd不引用其他库很难写

**Comment by langningchen** [comment]
> 但是Ztsd不引用其他库很难写

@boomzero 不仅要实现 C++ 版本，还要实现 JS 版本

**Comment by boomzero** [comment]
Js容易, c++难

**Comment by langningchen** [comment]
> Js容易, c++难
> […](#)
> On Oct 4, 2023, at 13:10, Chen LangNing ***@***.***> wrote:

确实

**Comment by langningchen** [comment]
所以就用更好的加密算法，就不用了，直接在获取不到数据的时候显示失败就行了

**Comment by langningchen** [comment]
还可以根据多次提交每次获取不同部分的数据，这样再拼接起来就能有完整的数据了 @boomzero @shihongxi @PythonSmall-Q

**Comment by langningchen** [comment]
比如先提交一次，把每一组数据的第一个数字获取出来，然后后来每一次提交判断第一个数字是否和你想要获取的那组数据的第一个数字符合，如果是再输出内容，否则就直接返回错误。

**Comment by shihongxi** [comment]
陈同学，您好。我这里是施泓熙家长邮箱，他不小心把我的邮箱作为注册邮箱了，最近几天频繁收到你们的邮件。能否麻烦您帮忙看看，如何操作才能不收到你们同学之间的交流信息？或者是否能在邮件发送是不抄送此邮箱？谢谢您。

---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 发送日期 | 2023年10月22日 08:56 |
| 收件人 | XMOJ-Script-dev/XMOJ-Script ***@***.***> |
| 抄送人 | shihongxi ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [XMOJ-Script-dev/XMOJ-Script] [Bug] 更改获取数据体验 (Issue #40) |

比如先提交一次，把每一组数据的第一个数字获取出来，然后后来每一次提交判断第一个数字是否和你想要获取的那组数据的第一个数字符合，如果是再输出内容，否则就直接返回错误。

**Comment by langningchen** [comment]
> 陈同学，您好。我这里是施泓熙家长邮箱，他不小心把我的邮箱作为注册邮箱了，最近几天频繁收到你们的邮件。能否麻烦您帮忙看看，如何操作才能不收到你们同学之间的交流信息？或者是否能在邮件发送是不抄送此邮箱？谢谢您。

这封邮件是我们在网页端发表回复后系统自动发送的，我们无法关闭，不过您可以在 https://github.com/settings/emails 更改接收通知邮箱或者使用被用邮箱 @shihongxi

**Comment by PythonSmall-Q** [comment]
施同学家长您好，非常抱歉邮件打扰了您的正常生活。像陈同学说的那样，您可以修改设置来避免打扰到您。
我对打扰到您感到非常抱歉。祝您生活愉快！
					——小明的OJ增强脚本开发组 单文骁

**Comment by langningchen** [comment]
> 施同学家长您好，非常抱歉邮件打扰了您的正常生活。像陈同学说的那样，您可以修改设置来避免打扰到您。
> 我对打扰到您感到非常抱歉。祝您生活愉快！
> 					——小明的OJ增强脚本开发组 单文骁

@PythonSmall-Q 终于上线了，CSP 考完了，赶快处理一下 issues ！ :tada:

**Comment by PythonSmall-Q** [comment]
> > 施同学家长您好，非常抱歉邮件打扰了您的正常生活。像陈同学说的那样，您可以修改设置来避免打扰到您。
> > 我对打扰到您感到非常抱歉。祝您生活愉快！
> > ——小明的OJ增强脚本开发组 单文骁
> 
> @PythonSmall-Q 终于上线了，CSP 考完了，赶快处理一下 issues ！ 🎉

修完一点了

**Comment by PythonSmall-Q** [comment]
wowwwwwwwwww！！！

**Comment by boomzero** [comment]
md:
```
/usr/bin/ld: /tmp/ccXNAcFV.o: in function `main':
Main.cc:(.text.startup+0x12d): undefined reference to `compressBound'
/usr/bin/ld: Main.cc:(.text.startup+0x15b): undefined reference to `compress'
collect2: error: ld returned 1 exit status
```

**Comment by PythonSmall-Q** [comment]
Xmoj不行？你可以看看hustoj评测机或者开issue问一下zhblue

**Comment by boomzero** [comment]
@PythonSmall-Q 我本地也不行qwq

**Comment by boomzero** [comment]
好像要开一个编译的flag

**Comment by boomzero** [comment]
准确来说是让linker link with zlib

**Comment by boomzero** [comment]
> Xmoj不行？你可以看看hustoj评测机或者开issue问一下zhblue

~就算他修了, 高老师也不会更新~

**Comment by langningchen** [comment]
> ~就算他修了, 高老师也不会更新~

@boomzero 🤣

**Comment by boomzero** [comment]
any ideas?

**Comment by langningchen** [comment]
Go on

**Comment by boomzero** [comment]
> Go on

@langningchen finally I am actually trying to fix this...

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/commit/fdc4601ca151630c6db47155279e1ff276d787e4

**Comment by langningchen** [comment]
Good!

**Comment by boomzero** [comment]
如果是增加报错，done
