### ISSUE TITLE
[Bug] 导出比赛排名表格显示异常

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#401]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

<img width="1372" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/f41e47e3-b7b1-4154-826f-12a82e8397dc">
建议: 使用xlsx而不是xls

**Comment by langningchen** [comment]
高老师原来的本来就是这样，他导出的是HTML格式
