### ISSUE TITLE
[Feature Request]希望可以随意查看标程

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#408]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

能在查看标程页面随意查看标程，但是有过“作弊者”称号的用户不允许随意查看
或者可以在题库页加一个标程功能

### 原因

无需细说

**Comment by langningchen** [comment]
~才发现自己好不要脸啊~

**Comment by PythonSmall-Q** [comment]
《一家公司的CEO》好像不是你对吧

**Comment by PythonSmall-Q** [comment]
我知道了，标程仅针对达到60分以上但是仍然有问题的代码

**Comment by boomzero** [comment]
50 分

**Comment by boomzero** [comment]
@zhouyiqing0304 其实呢, @PythonSmall-Q 没有写检测作弊者的代码, 所以作弊者其实是疑似提交当年代码的人……

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> 
> 
> ### 描述
> 
> 能在查看标程页面随意查看标程，但是有过“作弊者”称号的用户不允许随意查看 或者可以在题库页加一个标程功能
> ### 原因
> 
> 无需细说

~如果你需要, 可以私信我~

**Comment by boomzero** [comment]
@PythonSmall-Q 快传标程

**Comment by boomzero** [comment]
@zhouyiqing0304 这个实现不难, 但是~新功能必须得到pm @PythonSmall-Q 的同意~

**Comment by PythonSmall-Q** [comment]
和我有**关系，搞得像我独裁一样

**Comment by boomzero** [comment]
Emm

**Comment by boomzero** [comment]
cute swx

**Comment by PythonSmall-Q** [comment]
Emm最后一个说我cute的人是我的一位女性朋友（字面意思）

**Comment by boomzero** [comment]
<img width="401" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/e8b2466f-2b1e-4b16-bd8d-19a947625ccf">
~everyone knows that swx is a girl~

**Comment by langningchen** [comment]
@boomzero @PythonSmall-Q 你们俩说的有很对，我线下加过，可以证明他们都是可爱的女孩纸

**Comment by boomzero** [comment]
“他们“ 是谁……

**Comment by langningchen** [comment]
你和 @PythonSmall-Q

**Comment by boomzero** [comment]
And cln

**Comment by langningchen** [comment]
好吧……当个女孩纸也没什么问题 ~，反正我身边有好几个跨性别者~

**Comment by boomzero** [comment]
> 好吧……当个女孩纸也没什么问题 ~，反正我身边有好几个跨性别者~

???

**Comment by langningchen** [comment]
> ???
@boomzero “???”???

**Comment by PythonSmall-Q** [comment]
666
