### ISSUE TITLE
[Bug]提交页面下可能会遇到不让输入的情况

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#409]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

给一个屁用没有过的框子，点击也没反应

### 重现步骤

只要是提交页面就是这样

### 控制台错误信息

userscript.html?name=XMOJ.user.js&id=829a9a59-3694-4ceb-a652-79cc3cd5c13e:3673 {Success: true, Data: {…}, Message: '数据发送成功'}Data: {}Message: "数据发送成功"Success: true[[Prototype]]: Object
edit_area_full.js:2  Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at EAL.start (edit_area_full.js:2:5199)
    at <anonymous>:1:5
start @ edit_area_full.js:2
(匿名) @ VM4735:1
setTimeout(异步)
start @ edit_area_full.js:2
(匿名) @ VM4729:1
setTimeout(异步)
start @ edit_area_full.js:2
(匿名) @ VM4726:1
setTimeout(异步)
start @ edit_area_full.js:2
(匿名) @ VM4725:1
setTimeout(异步)
start @ edit_area_full.js:2
init @ edit_area_full.js:2
(匿名) @ submitpage.php?cid=6935&pid=0&langmask=5:99

**Comment by boomzero** [comment]
hmm

**Comment by boomzero** [comment]
@zhouyiqing0304 和 https://github.com/langningchen/XMOJ-Script/issues/26 一样吗

**Comment by boomzero** [comment]
哦, regression

**Comment by boomzero** [comment]
great...

**Comment by boomzero** [comment]
评价一下: 等几秒

**Comment by boomzero** [comment]
其实有两种方案:

1. 让整个脚本变得慢
2. 让个别功能变得慢

**Comment by boomzero** [comment]
@zhouyiqing0304 

可以开一下这个

<img width="1472" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/58a26eae-922c-44e6-9c60-78a4a9838e0d">

**Comment by zhouyiqing0304** [comment]
ok

**Comment by boomzero** [comment]
遗憾的是, 可以复现

**Comment by boomzero** [comment]
@zhouyiqing0304 fixed!

**Comment by boomzero** [comment]
@zhouyiqing0304 The fix is in dev
