### ISSUE TITLE
[Bug] 判断反了

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#41]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/bf59248419eeaa98e9a0f22d4041b89ac3ff8c44/XMOJ.user.js#L4092-L4097

4092行应当是`===`

**Comment by boomzero** [comment]
/-needs-triage
