### ISSUE TITLE
[Feature Request] use monaco-editor instead of codemirror

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#410]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/microsoft/monaco-editor

### 原因

solves #409 

And this is vscode!

**Comment by boomzero** [comment]
wip, but tommorrow

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/cd558724-19be-4764-aa1c-e772b4319f32)

不懂就问，这两个是什么东西？？？ @boomzero

**Comment by PythonSmall-Q** [comment]
哦我知道是什么了

**Comment by PythonSmall-Q** [comment]
我看了看还挺好的。可以试试看，但是会不会让script加载速度变慢

**Comment by boomzero** [comment]
@PythonSmall-Q 我昨天写着写着要疯了

**Comment by boomzero** [comment]
他tm是AMD script, 还有自己的loader

**Comment by PythonSmall-Q** [comment]
对，那你还是不要放了吧。先把https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/364 解决掉（？

**Comment by boomzero** [comment]
本地调试模式是和 wrangler dev 一起用的, 用来调试后台

**Comment by boomzero** [comment]
No, I want to do this

**Comment by boomzero** [comment]
because jquery is causing stupid errors, I give up /wontfix

**Comment by langningchen** [comment]
@boomzero 
- https://youtu.be/dQw4w9WgXcQ
-
