### ISSUE TITLE
[Feature Request] tell users to use violentmonkey

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#417]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/violentmonkey/violentmonkey

### 原因

It works and it is open source!

**Comment by PythonSmall-Q** [comment]
why？？？

**Comment by PythonSmall-Q** [comment]
violentmonkey语法报错，然而我看不到错在哪里ovo

**Comment by boomzero** [comment]
不可能, 请使用最新预览版

**Comment by boomzero** [comment]
nope, there are bugs /invalid
