### ISSUE TITLE
[Bug] 短消息功能暂时丧失、怎样查看后台标程、怎样Pull Request

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#421]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://www.xmoj.tech/mail.php
一直加载
希望我能随便查看标程
怎么pull request

**Comment by langningchen** [comment]
> 怎样Pull Request

...

**Comment by boomzero** [comment]
@zhouyiqing0304 
<img width="1157" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/6b920348-0550-4842-981c-97b5567a2b59">
cannot reproduce

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。
> 
> 
> ### 描述
> 
> https://www.xmoj.tech/mail.php 一直加载 希望我能随便查看标程 怎么pull request
> ### 重现步骤
> 
> _No response_
> ### 控制台错误信息
> 
> _No response_

~有可能当时我在更新后台~

**Comment by boomzero** [comment]
ps, 标程url: `https://www.xmoj.tech/showsource.php?pid=<题目编号>&ByUserScript=1`

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 pr的话是修改dev分支，然后pr到dev，pr的标题是更新内容

**Comment by PythonSmall-Q** [comment]
到master会被自动关闭
