### ISSUE TITLE
[Feature Request]小明OJ的讨论功能中引用之后聊天框会显示要引用的消息，并用> 表示，这样很影响体验

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#430]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

（_@shanwenxiao_ : 名誉管理： @admi . . . ）
回复
┌───┐
│赞成 │
└───┘

### 原因

要有更好的体验

**Comment by zhouyiqing0304** [comment]
@boomzero @PythonSmall-Q 后台的代码我会小改一下

**Comment by boomzero** [comment]
> @boomzero @PythonSmall-Q 后台的代码我会小改一下

@zhouyiqing0304  ~emm, can you port the backend to https://nitro.unjs.io/~

**Comment by boomzero** [comment]
> ### 检查项
> 
>     * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> 
>     * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> 
> 
> ### 描述
> 
> （_@shanwenxiao_ : 名誉管理： @admi . . . ） 回复 ┌───┐ │赞成 │ └───┘
> ### 原因
> 
> 要有更好的体验

github 不也是吗

**Comment by zhouyiqing0304** [comment]
> > ### 检查项
> > ```
> > * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> > 
> > * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 描述
> > （_@shanwenxiao_ : 名誉管理： @admi . . . ） 回复 ┌───┐ │赞成 │ └───┘
> > ### 原因
> > 要有更好的体验
> 
> github 不也是吗

何必呢，不要为差的体验找理由，我会研究一下的

**Comment by boomzero** [comment]
> > > ### 检查项
> > > ```
> > > * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> > > 
> > > * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 描述
> > > （_@shanwenxiao_ : 名誉管理： @admi . . . ） 回复 ┌───┐ │赞成 │ └───┘
> > > ### 原因
> > > 要有更好的体验
> > 
> > 
> > github 不也是吗
> 
> 何必呢，不要为差的体验找理由，我会研究一下的

你让我很无语……

**Comment by boomzero** [comment]
1. This is standard markdown
2. This is standard for many platforms and is a **feature**
3. It doesn't affect UX

**Comment by langningchen** [comment]
@boomzero 说的很对，有句名言说：

> It's not a bug, it's a feature.

**Comment by PythonSmall-Q** [comment]
> @boomzero @PythonSmall-Q 后台的代码我会小改一下

别直接改，先pr到xmoj-bbs里面，大家讨论之后再改
