### ISSUE TITLE
[Feature Request]讨论功能欠缺搜索功能

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#431]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

[讨论](https://www.xmoj.tech/discuss3/discuss.php)区应有搜索功能，方便更快捷的查找讨论内容

### 原因

@langningchen @boomzero @PythonSmall-Q 有人能帮得上忙的赶紧来

**Comment by boomzero** [comment]
~good luck~

**Comment by langningchen** [comment]
我帮忙不了，但是我觉得这是一个好主意

**Comment by boomzero** [comment]
~~我帮忙不了，但是我觉得这不是一个好主意~~

**Comment by langningchen** [comment]
> ~我帮忙不了，但是我觉得这不是一个好主意~

Why? It's easy! If a am the developer now, I can do it within half an hour!

**Comment by boomzero** [comment]
Yes, Yes, of courseI know what you want to do, Select + like, but it is inefficient and stupid and can be abused, you at least have to implement some kind of indexing, so good luck.PS: why would anyone want to search through discussions, it’s not like there is any useful information 发自我的 iPhone在 2024年2月10日，12:44，Langning Chen ***@***.***> 写道：﻿

我帮忙不了，但是我觉得这不是一个好主意

Why? It's easy! If a am the developer now, I can do it within half an hour!

**Comment by boomzero** [comment]
Then, submit a pr!发自我的 iPhone在 2024年2月10日，12:44，Langning Chen ***@***.***> 写道：﻿

我帮忙不了，但是我觉得这不是一个好主意

Why? It's easy! If a am the developer now, I can do it within half an hour!

**Comment by boomzero** [comment]
note: algolia.com

**Comment by PythonSmall-Q** [comment]
1. 耗费大量服务器资源
2. 每次搜索如果需要搜寻回复则需要类似index的db
so wontfix /wontfix
