### ISSUE TITLE
[Bug] 右上角用户名点击后无反应

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#433]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/04173710-3c4f-4cbf-8cd8-9fa821050cc8

### 重现步骤

use 
<img width="842" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/eabb5241-6582-4a0a-9629-fa2d900d0783">

### 控制台错误信息

JavaScript error: https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.0-alpha3/js/bootstrap.min.js, line 6: TypeError: s.createPopper is not a function

**Comment by boomzero** [comment]
note: this does not happen in the latest non-beta release of firefox

**Comment by boomzero** [comment]
but, if you build firefox from source yourself, this will happen

**Comment by PythonSmall-Q** [comment]
所以这和script有什么关系

**Comment by PythonSmall-Q** [comment]
这个是没加载完就点了东西所以出的问题，我有时候vpn慢也会出这个问题

**Comment by boomzero** [comment]
> 这个是没加载完就点了东西所以出的问题，我有时候vpn慢也会出这个问题

加载完了也不行

**Comment by boomzero** [comment]
> 这个是没加载完就点了东西所以出的问题，我有时候vpn慢也会出这个问题

~这个功能我写的, 我当然知道~

**Comment by boomzero** [comment]
> 这个是没加载完就点了东西所以出的问题，我有时候vpn慢也会出这个问题

请使用unpkg CDN

**Comment by boomzero** [comment]
Can reproduce in Edge

**Comment by boomzero** [comment]
fixed

**Comment by langningchen** [comment]
I'm stupid to use `popper.js` 🤭
