### ISSUE TITLE
[Feature Request]我要改一下后台的程序

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#434]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

我需要改一下后台的程序！！！！！！！！！！！
@boomzero @PythonSmall-Q @langningchen 

### 原因

！！！！！！！！！！

**Comment by langningchen** [comment]
你改呀

**Comment by langningchen** [comment]
又没人拦着你

**Comment by langningchen** [comment]
具体怎么操作我不是已经给你发邮件了吗？

**Comment by langningchen** [comment]
有哪里你看不懂吗？

**Comment by langningchen** [comment]
![Screenshot_20240204_110441](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/40e9112a-afe7-4fa9-890f-ddccf500a72e)

**Comment by zhouyiqing0304** [comment]
ok

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 你要改代码的话pr到xmoj-script-dev/xmoj-bbs，我们看完了再deploy否则出问题很烦的
