### ISSUE TITLE
[Bug] fix tidytable

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#44]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

http://www.xmoj.tech/index.php 的表格也要增加边框

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/da9e6ea5-2bc4-417a-9fc4-9ebef9ac66fd)

**Comment by boomzero** [comment]
conflicts with #48

**Comment by boomzero** [comment]
tidytable 有毒

**Comment by boomzero** [comment]
表格有没有边框不重要

**Comment by boomzero** [comment]
#48 重要

**Comment by boomzero** [comment]
> tidytable 有毒

fixed
