### ISSUE TITLE
[Feature Request] 图床优化

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#45]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

上传图片时应当像 GitHub 一样显示 Uploading Image ，并且将上传好插入的 MarkDown 插入到光标位置，而不是编辑框的最后

**Comment by PythonSmall-Q** [comment]
啊？使光标位置啊？我这里都是在光标位置上的

**Comment by langningchen** [comment]
你应该自己看看，好像是在末尾的

**Comment by langningchen** [comment]
如果是在光标位置，那么就在上传图片时应当像 GitHub 一样显示 Uploading Image

**Comment by PythonSmall-Q** [comment]
我去看看

**Comment by PythonSmall-Q** [comment]
但是这样比较烦

**Comment by PythonSmall-Q** [comment]
emm好像是的

**Comment by boomzero** [comment]
/-priority-high /priority-low

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/8d9b1d2b-a3c7-489a-94c3-700625b410bf)
XMOJ.user.js 代码3909行+=即在最后贴上图片

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by boomzero** [comment]
你这个回复时间...

**Comment by PythonSmall-Q** [comment]
> 你这个回复时间...

有时间帮我看看呗 @boomzero

**Comment by PythonSmall-Q** [comment]
@langningchen fixed。你看看能不能更新

**Comment by boomzero** [comment]
> @boomzero 你去[这个branch](https://github.com/XMOJ-Script-dev/XMOJ-Script/tree/45-feature-request-better-images)帮我看一下为什么贴图之后会删除之前所有的内容

无法复现

**Comment by boomzero** [comment]
但是我·用不了图床

**Comment by boomzero** [comment]
只能把图床代码复制到console执行

**Comment by boomzero** [comment]
> 但是我·用不了图床

可以用了

**Comment by boomzero** [comment]
![](https://api.xmoj-bbs.tech/GetImage?ImageID=lmkgqsehmzpybmeonklbnajvwqwcgfse)

**Comment by langningchen** [comment]
这个图标左面红色的好像是 `dp` 欸

**Comment by PythonSmall-Q** [comment]
不是dp我记得当时的创造理念是对称的（收洛谷启发

**Comment by langningchen** [comment]
> 不是dp我记得当时的创造理念是对称的（收洛谷启发

哦
