### ISSUE TITLE
[Bug]某些题目内容在暗黑模式下显示异常

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#456]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/94766918/da086d90-6ad3-4be6-ba59-ef1ef766c7c6)
这个loong看不清楚

### 重现步骤

cid=6955
2024/2 Div2 第一题

### 控制台错误信息

没有错误

**Comment by PythonSmall-Q** [comment]
题目看不到，能不能把源代码发我？

**Comment by boomzero** [comment]
报名月赛发自我的 iPhone在 2024年2月17日，10:58，Shan Wenxiao ***@***.***> 写道：﻿
题目看不到，能不能把源代码发我？

**Comment by PythonSmall-Q** [comment]
感觉这个是xmoj自身特性？

**Comment by PythonSmall-Q** [comment]
> 感觉这个是xmoj自身特性？

@boomzero is it？

**Comment by boomzero** [comment]
不是, 你把script 关掉你就知道了

**Comment by boomzero** [comment]
This is very hard to fix

**Comment by boomzero** [comment]
It is simply very hard

**Comment by boomzero** [comment]
very very hard

**Comment by boomzero** [comment]
unless you want to rerender the entire page yourself

**Comment by boomzero** [comment]
or spend several hours debugging an old version of mathjax

**Comment by boomzero** [comment]
I am closing this stupid cosmetic issue

**Comment by boomzero** [comment]
explanation: We need to somehow block xmoj's mathjax(hard) and render the page with our mathjax(easy)
