### ISSUE TITLE
[Feature Request] 优化标签页标题显示

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#46]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

比如此页面，标题不应为 `高老师的OJ` ，而应该为 `问题3503状态`

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/d17ca9d4-43c6-4660-987f-fb54e9102f35)

**Comment by PythonSmall-Q** [comment]
为啥你这里可以看到运行编号（？？

**Comment by langningchen** [comment]
我不知道

**Comment by langningchen** [comment]
你是哪道题目看不到运行编号？

**Comment by PythonSmall-Q** [comment]
我太吓人了，一点还在学习

**Comment by boomzero** [comment]
> ### 检查项
> * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
> * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。
> 
> ### 描述
> 比如此页面，标题不应为 `高老师的OJ` ，而应该为 `问题3503状态`
> 
> ![image](https://private-user-images.githubusercontent.com/81672884/272214488-d17ca9d4-43c6-4660-987f-fb54e9102f35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MzE1NTYsIm5iZiI6MTcwNzUzMTI1NiwicGF0aCI6Ii84MTY3Mjg4NC8yNzIyMTQ0ODgtZDE3Y2E5ZDQtNDNjNi00NjYwLTk4N2YtZmI1NGU5MTAyZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDAyMTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMjc4MjMwNjU3NWFlY2IxNTM3ZDYwMGVlMDBiYjQxYzc4MWEyMmNmMTc5ZTFiNTg0OWJiODIwNjA2MzYyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZGYYz3c8oUez1Rh19qQYcBynkK2xgfy8KhN9C3rsB4o)
> 
> ### 原因
> _No response_

I approve

**Comment by boomzero** [comment]
更重要的是讨论区

**Comment by langningchen** [comment]
这是十月份提出的需求，你们现在还没有完成

**Comment by boomzero** [comment]
…在 2024年2月10日，14:00，Langning Chen ***@***.***> 写道：﻿
这是十月份提出的需求，你们现在还没有完成

**Comment by boomzero** [comment]
We are all volunteers, so we make no guarantees about upcoming features, however, we welcome pull requests.发自我的 iPhone在 2024年2月10日，14:00，Langning Chen ***@***.***> 写道：﻿
这是十月份提出的需求，你们现在还没有完成

**Comment by langningchen** [comment]
PR......

**Comment by boomzero** [comment]
怎么了在 2024年2月11日，10:36，Langning Chen ***@***.***> 写道：﻿
PR......

**Comment by langningchen** [comment]
没什么

**Comment by boomzero** [comment]
> 这是十月份提出的需求，你们现在还没有完成，即使我不在，你们也要有积极性

.

**Comment by boomzero** [comment]
不过比较好笑的是, 你截图的那一页没加

**Comment by boomzero** [comment]
> 不过比较好笑的是, 你截图的那一页没加

加了

**Comment by boomzero** [comment]
还有conteststatistics.php

**Comment by langningchen** [comment]
？

**Comment by boomzero** [comment]
done
