### ISSUE TITLE
[Feature Request] 为团队设置头像

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#47]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

RT

**Comment by PythonSmall-Q** [comment]
fixed

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by boomzero** [comment]
Why is this even an issue…
