### ISSUE TITLE
[Feature Request]希望脚本可以自动上传老师给出的标程

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#472]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

如果老师有标程，且服务器没有这个标程，就自动上传

### 原因

xmoj脚本的std可以更丰富

**Comment by boomzero** [comment]
加油在 2024年2月18日，20:58，zhouyiqing0304 ***@***.***> 写道：﻿
检查项

 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
 我已在 Issues 页面 中搜索，确认了这一提案未被提交过。

描述
如果老师有标程，且服务器没有这个标程，就自动上传
谁写过上传标程的代码的，在哪里，没有注释啊
@PythonSmall-Q 你写一个服务器函数判断是否有这个题目编号的标程，没有就返回false，有就返回true
原因
xmoj脚本的std可以更丰富

**Comment by zhouyiqing0304** [comment]
@boomzero 请赶紧回复这个玩意儿是干嘛的

**Comment by PythonSmall-Q** [comment]
加油

**Comment by PythonSmall-Q** [comment]
@zhouyiqing0304 关于您的功能提议，脚本本身就具有自动上传老师代码的功能。具体可以去问langningchen我有点忘了在哪里了（也没空去找）

**Comment by PythonSmall-Q** [comment]
why close?
