### ISSUE TITLE
[Feature Request] 复制样例

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#48]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

部分题目复制样例有 BUG ，比如 http://www.xmoj.tech/problem.php?cid=6480&pid=0  https://www.xmoj.tech/problem.php?cid=6659&pid=2 等等

**Comment by langningchen** [comment]
@PythonSmall-Q 逐步 Debug 调试啊

**Comment by PythonSmall-Q** [comment]
然而并没有发现这个prob的html格式和其他的什么问题 @boomzero 你看看能找到啥吗？/help-wanted

**Comment by langningchen** [comment]
难道又要我来调试吗？仔细看一看，我不也是像你这样一步一步看嘛，我也没什么好方法

**Comment by boomzero** [comment]
@langningchen is this fixed? I cannot check
<img width="1338" alt="image" src="https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/768bb3a7-bcce-4536-a25e-95507475ad5e">

**Comment by PythonSmall-Q** [comment]
no 
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/5061a457-ea60-4490-8aee-70851955b582)

**Comment by boomzero** [comment]
@PythonSmall-Q another example https://www.xmoj.tech/problem.php?cid=6659&pid=2

**Comment by boomzero** [comment]
共同点是都有表格

**Comment by boomzero** [comment]
所以是tidytable干的?

**Comment by langningchen** [comment]
很有可能
