### ISSUE TITLE
[Feature Request]在提交界面显示freopen语句缺失可以自动添加、freopen语句被注释可以自动取消注释

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#501]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

加一个自动改正的按钮用以自动添加freopen与自动去注释

**Comment by PythonSmall-Q** [comment]
这个的话一切取决于用户自己，有时候会误判

**Comment by boomzero** [comment]
Maybe we give the user the correct freopen and let them paste it in.

**Comment by boomzero** [comment]
Idea by another user, I think

**Comment by zhouyiqing0304** [comment]
我自己想到的，因为老是不写这个freopen
另外你这个建议很不错啊，我可以写出来

**Comment by boomzero** [comment]
> 我自己想到的，因为老是不写这个freopen 另外你这个建议很不错啊，我可以写出来

Okay

**Comment by zhouyiqing0304** [comment]
> 加油 （bushi
你这个昵称误导性很强啊，险些不认识你是ptsq

**Comment by zhouyiqing0304** [comment]
@PythonSmall-Q @boomzero https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/641
