### ISSUE TITLE
[Feature Request] 自动粘贴代码

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#51]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

在进入 submitpage.php 时，如果粘贴板里面时代码（提示：检测第一个字符是否是`#`、内容中是否有字符串`main`），则自动粘贴到代码框并显示出提交按钮（提示：使用函数 `scrollIntoView`）

**Comment by boomzero** [comment]
6 /-needs-triage /investigating /priority-low

**Comment by PythonSmall-Q** [comment]
贴代码是oier的基本能力，这项功能削弱了oier必备的品格。同时，自动黏贴损害了用户的选择权和知情权，我认为wontfix？你们呢

**Comment by boomzero** [comment]
> 贴代码是oier的基本能力，这项功能削弱了oier必备的品格。同时，自动黏贴损害了用户的选择权和知情权，我认为wontfix？你们呢

emm

**Comment by boomzero** [comment]
1. I don;t think this is necessary
2. This could save at most 2 seconds
3. This would cause glitches if it fails
So...

**Comment by langningchen** [comment]
我随便
