### ISSUE TITLE
[Bug] Auto Read自动阅读对方未读的消息

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#520]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Relates to https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/517 会自动read发给别人的消息 比如我给 @boomzero 发的消息

### 重现步骤

如描述

### 控制台错误信息

N/A

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by boomzero** [comment]
fixed
