### ISSUE TITLE
[Bug]部分题目样例数据显示错误 【与#48重复】

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#540]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/94766918/917f8016-46ea-4a1d-8141-d6a518cdb875)
如图可见

### 重现步骤

问题题目编号：3600

**Comment by PythonSmall-Q** [comment]
same as https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/48
