### ISSUE TITLE
[Feature Request] cache discussions in localstorage

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#56]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

rt

### 原因

related to #18

**Comment by PythonSmall-Q** [comment]
emm这样不能保证时效性

**Comment by PythonSmall-Q** [comment]
比如说我在0ms的时候发了一个帖子“qwq”然后比如说admin访问了bbs cache了这个，但是下一秒我又发了一个帖子“ovo”，这样admin就没有cache，就显示不出来

**Comment by PythonSmall-Q** [comment]
我觉得还是先解决访问冗余的问题

**Comment by boomzero** [comment]
> 比如说我在0ms的时候发了一个帖子“qwq”然后比如说admin访问了bbs cache了这个，但是下一秒我又发了一个帖子“ovo”，这样admin就没有cache，就显示不出来

可以cache有效期10秒

**Comment by PythonSmall-Q** [comment]
那还叫cache？？？

**Comment by PythonSmall-Q** [comment]
我觉得这个cache不好，我们还是专注于解决冗余的问题吧 /invalid
