### ISSUE TITLE
[Bug] 板块页面切换引导错误

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#562]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

板块页面切换引导错误，即应该是https://www.xmoj.tech/discuss3/discuss.php?bid=0&page=2 变成了https://www.xmoj.tech/discuss3/discuss.php?page=2

### 重现步骤

1. 点开讨论
2. 点击“站务版”/“灌水版”/any other（貌似题目专版的题目内部是可以的）
3. 点击上部引导栏“2”/“3”/...
4. 发现问题

**Comment by boomzero** [comment]
No! Don't paste console logs, they include your phpsessid

**Comment by boomzero** [comment]
Can reproduce

**Comment by PythonSmall-Q** [comment]
我删掉了都

**Comment by boomzero** [comment]
fixed
