### ISSUE TITLE
[Bug] ACM排名表格异常

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#582]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

省流：缺少用户做的题目

![image](https://github.com/user-attachments/assets/12831ee4-7b24-4b16-b5b3-bdf481ffc2e2)

**Comment by PythonSmall-Q** [comment]
@boomzero

**Comment by boomzero** [comment]
https://www.xmoj.tech/contestrank-oi.php?cid=6009&ByUserScript=1

**Comment by PythonSmall-Q** [comment]
定位问题，艹

**Comment by PythonSmall-Q** [comment]
高老师的锅
