### ISSUE TITLE
[Feature Request]更多动画效果

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#584]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

确定不是[More Graphics](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues/545)一栏，那是图形效果，不是动画效果

你们很需要一些舒服的功能，如在[题库](https://www.xmoj.tech/problemset.php)中顶栏
![image](https://github.com/user-attachments/assets/85358e8f-80bb-4d19-9f53-7cf024067aa4)
不与页面一起上滑，而是存在一个模糊效果
![image](https://github.com/user-attachments/assets/846b68da-48db-422b-9071-b373cf43ef39)
像这样

### 原因

看着肚子不舒服

**Comment by zhouyiqing0304** [comment]
虽然实现难度不亚于重新写一个

**Comment by PythonSmall-Q** [comment]
加油~（bushi

**Comment by PythonSmall-Q** [comment]
（大型期待

**Comment by zhouyiqing0304** [comment]
> （大型期待

哈哈哈哈结果期待了半天一场空(bushi)
