### ISSUE TITLE
[Bug] 部分用户主页加载失败

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#589]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

e.g.  https://www.xmoj.tech/userinfo.php?user=zhuyiyang

**Comment by boomzero** [comment]
Can not reproduce

**Comment by boomzero** [comment]
<img width="1992" alt="image" src="https://github.com/user-attachments/assets/eccc5045-0f16-4ede-8b5a-f2b37f2d8b6a">

**Comment by PythonSmall-Q** [comment]
网络慢的话会

**Comment by boomzero** [comment]
> 网络慢的话会

那就等吧
