### ISSUE TITLE
[Feature Request] 将讨论给openai moderation endpoint过滤

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#60]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://platform.openai.com/docs/guides/moderation/overview
是免费的

### 原因

~防止 @PythonSmall-Q 被网管请去喝茶~

**Comment by PythonSmall-Q** [comment]
可以

**Comment by PythonSmall-Q** [comment]
数据安全问题

**Comment by PythonSmall-Q** [comment]
违反了《中华人民共和国个人信息保护法》

**Comment by PythonSmall-Q** [comment]
和《个人信息出境标准合同办法》。我们没有通过安全审查

**Comment by PythonSmall-Q** [comment]
我们符合
>（一）数据处理者向境外提供重要数据；
传输公民姓名到境外

**Comment by PythonSmall-Q** [comment]
https://www.gov.cn/zhengce/zhengceku/2022-07/08/content_5699851.htm

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/877b1eb2-7337-4b25-bffd-f75ca5696244)

**Comment by boomzero** [comment]
> 我们符合
> 
> > （一）数据处理者向境外提供重要数据；
> > 传输公民姓名到境外

6

**Comment by PythonSmall-Q** [comment]
因为违法所以不准备做了 /invalid

**Comment by boomzero** [comment]
why?

**Comment by boomzero** [comment]
只传讨论啊

**Comment by boomzero** [comment]
/-invalid

**Comment by boomzero** [comment]
我知道是什么回事, 但是@actions 好吓人

**Comment by boomzero** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/c99d2d1c-3009-41c7-bc22-bea9eac3bfe8)

**Comment by PythonSmall-Q** [comment]
好像只有我能手工去除标签，你必须要用命令行

**Comment by PythonSmall-Q** [comment]
那就你做了

**Comment by PythonSmall-Q** [comment]
/working-on-it /priroty-low 我知道了，不能再发言之后，actions运行完之前add，斗则自动删除

**Comment by boomzero** [comment]
对

**Comment by boomzero** [comment]
我的openai号用不了了... /wontfix

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/85378277/85423b00-58f1-4583-a498-0170f29ce592)
