### ISSUE TITLE
[Bug]获取题目分数失败

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#606]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/3498495e-2ae3-48fb-9ee3-8b42bac27823)
![image](https://github.com/user-attachments/assets/36a59c39-83f7-45f8-8bc8-ad74a029461e)
如果第二次提交了低于50分的分数，然后再看标程就会检测出错误

### 重现步骤

提交第一次>50分，然后再提交一次<50分，再点击第一次提交的查看标程，会获取题目分数失败

**Comment by PythonSmall-Q** [comment]
刷新一下

**Comment by PythonSmall-Q** [comment]
会有延迟，我也复现一下

**Comment by PythonSmall-Q** [comment]
不能复现

**Comment by zhouyiqing0304** [comment]
仍然不行

**Comment by boomzero** [comment]
By design

**Comment by boomzero** [comment]
不会有人这样做

**Comment by boomzero** [comment]
> 仍然不行

是网络原因, 无法解决, 和你说的东西无关
