### ISSUE TITLE
[Bug]个人信息栏（导航栏右侧）动画打断会显示错误

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#610]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

已经在修复了

### 重现步骤

快速双击姓名栏（如shanwenxiao↓），注销（或者插件设置）会在一瞬间明亮，此时本应不显示

### 控制台错误信息

控制台无错误

**Comment by zhouyiqing0304** [comment]
![image](https://github.com/user-attachments/assets/51b82b31-672a-4f38-a539-218775a0a100)

**Comment by boomzero** [comment]
这个应该问题不大吧? 还是把动画调快一点, ~等不及~ @z
