### ISSUE TITLE
[Bug]一路向右延申到遥远的天边. . . . . .

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#617]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/b68f58cd-cb62-42ff-9436-401644f637e2)

**Comment by zhouyiqing0304** [comment]
短消息就是有这个bug，一路延申
![image](https://github.com/user-attachments/assets/f2134206-c17e-481b-81c4-9595d54e17f5)

**Comment by PythonSmall-Q** [comment]
这个一直有，因为发了很长的东西，就默认延伸。之前发现了，感觉问题不大就没开issue

**Comment by boomzero** [comment]
延伸长度=你发的最长消息长度, 而不是无限延伸

**Comment by boomzero** [comment]
可以把container调小一点, 如果太长
