### ISSUE TITLE
[Bug] Fix https://www.xmoj.tech/open_contest_sign_up.php

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#620]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Perhaps by substituting hidden with visually-hidden

**Comment by zhouyiqing0304** [comment]
这一栏没有脚本？

**Comment by zhouyiqing0304** [comment]
ok修好了

**Comment by boomzero** [comment]
> 这一栏没有脚本？

脚本会导致报名失败

**Comment by boomzero** [comment]
所以手动关了

**Comment by zhouyiqing0304** [comment]
不确定啊

**Comment by zhouyiqing0304** [comment]
脚本理论上不会影响

**Comment by boomzero** [comment]
等到有月赛时再说吧

**Comment by boomzero** [comment]
Test
