### ISSUE TITLE
[Docs] Write actual documentation 

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#621]
### 检查项

- [X] 我已确认了帮助文档已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Self-explanatory

**Comment by PythonSmall-Q** [comment]
assign我干嘛

**Comment by PythonSmall-Q** [comment]
**的有*病嘛

**Comment by boomzero** [comment]
> **的有*病嘛

@PythonSmall-Q 自己配制的自动assign你, ~我能有什么办法~ :)

**Comment by PythonSmall-Q** [comment]
哦（委屈巴巴

**Comment by boomzero** [comment]
> 哦（委屈巴巴

And write docs, please 🦔

**Comment by PythonSmall-Q** [comment]
@boomzero 详细解释一下

**Comment by boomzero** [comment]
写文档呗! 介绍rating机制, 各种功能...

**Comment by PythonSmall-Q** [comment]
你知道写mkdocs有多烦吗

**Comment by boomzero** [comment]
那用Jetbrains writerside!

**Comment by boomzero** [comment]
https://www.jetbrains.com/writerside/

**Comment by boomzero** [comment]
https://github.com/XMOJ-Script-dev/docs-v2 用的就是这个

**Comment by PythonSmall-Q** [comment]
不可能

**Comment by boomzero** [comment]
...

**Comment by boomzero** [comment]
Why not

**Comment by PythonSmall-Q** [comment]
migrate不方便，mkdocs写习惯了

**Comment by boomzero** [comment]
> migrate不方便，mkdocs写习惯了

我帮你migrate 好了

**Comment by boomzero** [comment]
> https://github.com/XMOJ-Script-dev/docs-v2 用的就是这个

**Comment by PythonSmall-Q** [comment]
不用

**Comment by boomzero** [comment]
merge

**Comment by boomzero** [comment]
the pr

**Comment by PythonSmall-Q** [comment]
https://github.com/XMOJ-Script-dev/docs/tree/upd-2024Aug
