### ISSUE TITLE
[Feature Request] 用户主页允许用户设置个性签名

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#63]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

想起来说过要做关注，但是觉得没必要搞关注。我们做允许用户设置个性签名吧~

**Comment by PythonSmall-Q** [comment]
喵呜这可是一个很好的功能捏

**Comment by boomzero** [comment]
可以吧

**Comment by boomzero** [comment]
?

**Comment by langningchen** [comment]
@PythonSmall-Q ？

**Comment by boomzero** [comment]
突然发现个性签名在xmoj中就是昵称
