### ISSUE TITLE
[Feature Request]自动补充freopen语句

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#638]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

提示没有freopen语句的时候加一个按钮，用于询问用户是否需要自动补充freopen语句并提交

**Comment by boomzero** [comment]
Duplicate of #501

**Comment by boomzero** [comment]
Small bug that nobody wants to fix

**Comment by boomzero** [comment]
…
