### ISSUE TITLE
[Feature Request] 更改宣传图片 

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#65]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

有一些在网站上和 README.md 上面的图片已经过时了，需要更新

**Comment by PythonSmall-Q** [comment]
收到 /working-on-it

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by langningchen** [comment]
@PythonSmall-Q 还有问题

**Comment by langningchen** [comment]
Image07 有两个没加载出来，导致效果展现的不好

**Comment by langningchen** [comment]
~~为什么我没法 reopen？ Author 因该是可以的吧？~~

**Comment by PythonSmall-Q** [comment]
Author不能reopen

**Comment by PythonSmall-Q** [comment]
/-working-on-it
