### ISSUE TITLE
[Bug] `Compare.md` 有误

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#66]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

应当适当根据当前情况修改 ~~，另外我说句闲话 ChatGPT 那一行你删掉吧，因为当时我在前面跟她说了怎么回复，所以她才有观点的，不然她应该回答说不清楚~~

**Comment by PythonSmall-Q** [comment]
哦我忘记把compare改掉了，谢谢提醒！喵呜题目做不出来qwq

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by PythonSmall-Q** [comment]
fixed /-working-on-it
