### ISSUE TITLE
[Bug] Script 无论如何都会打开O2提交

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#672]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

包括如果用户关闭O2

**Comment by zhouyiqing0304** [comment]
@boomzero 
![image](https://github.com/user-attachments/assets/b133ba89-f3e3-4c4a-99dc-fe926bae71c6)

**Comment by zhouyiqing0304** [comment]
你们这不是写死了开O2嘛

**Comment by zhouyiqing0304** [comment]
......

**Comment by zhouyiqing0304** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/679

**Comment by zhouyiqing0304** [comment]
@boomzero 可以关了
