### ISSUE TITLE
[Bug]不要短时间大量更新，尽可能将多个更新整合

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#675]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

烦死了，今天半天就一堆更新，不下十个
@boomzero 你慢一点

**Comment by boomzero** [comment]
> ### 检查项
> * [x]  我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
> * [x]  我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。
> 
> ### 描述
> 烦死了，今天半天就一堆更新，不下十个 @boomzero 你慢一点
> 
> ### 重现步骤
> _No response_
> 
> ### 控制台错误信息
> _No response_

好的不干活了
