### ISSUE TITLE
[Bug] 修改用户信息失败

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#701]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

修改用户信息，点确定，刷新发现没改

**Comment by boomzero** [comment]
Can reprduce

**Comment by zhouyiqing0304** [comment]
2024/8/16 13:29:12
复现失败
![image](https://github.com/user-attachments/assets/27ebc279-3fea-4b3f-9598-654d41f767e1)
改的是
![image](https://github.com/user-attachments/assets/27a4f89b-009e-4353-8d87-d8c5a1998c07)
