### ISSUE TITLE
[Bug] 代码长度单位换算错误

### ISSUE THREAD

**Issue by SunburstFan1106** [XMOJ-Script-dev/XMOJ-Script#706]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

状态页面 代码长度默认单位为B，换算时多乘了1000

**Comment by boomzero** [comment]
哦原来和内存不一样

**Comment by boomzero** [comment]
如果论简单，这个真简单 @PythonSmall-Q
