### ISSUE TITLE
[Bug]能不能别把我的姓名就这么印上去

### ISSUE THREAD

**Issue by zhouyiqing0304** [XMOJ-Script-dev/XMOJ-Script#720]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/user-attachments/assets/931ec3de-1ff5-4f23-bc4c-53b54a330028)
快点删掉我的名字
不要未经我的允许就这么干啊

**Comment by boomzero** [comment]
nope

**Comment by boomzero** [comment]
你同意了用户协议
