### ISSUE TITLE
[Bug] 更新死循环

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#76]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

@PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero @PythonSmall-Q @boomzero 

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/23e9d86a-2d26-47c3-a1cb-a95aeeb80c6f)

更新后还是 `1.0.205` ，而不是 `1.0.207`

**Comment by langningchen** [comment]
快来看啊啊啊啊啊！！！

**Comment by PythonSmall-Q** [comment]
我知道。现在选修了

**Comment by PythonSmall-Q** [comment]
fixed，在更新一下

**Comment by langningchen** [comment]
好了

**Comment by PythonSmall-Q** [comment]
之前忘记关automerge，把那个没修好的image upload传到master了，然后赶紧回滚部署

**Comment by langningchen** [comment]
@PythonSmall-Q 你么以后正式版本不要发布的这么勤快

**Comment by langningchen** [comment]
大约一周发一次就够了

**Comment by PythonSmall-Q** [comment]
emm这是github的锅

**Comment by langningchen** [comment]
你们 Dev Channel 可以发的快一点

**Comment by PythonSmall-Q** [comment]
/-investigating

**Comment by PythonSmall-Q** [comment]
关键dev有个图床的锅还在那里

**Comment by langningchen** [comment]
你们慢慢修吧，如果有什么不明白的再问我

**Comment by PythonSmall-Q** [comment]
会莫名奇妙地删除所有内容替换成图片

**Comment by langningchen** [comment]
> 会莫名奇妙地删除所有内容替换成图片

？什么东西？

**Comment by PythonSmall-Q** [comment]
你尝试用一下45-。。。-image分支地js就知道什么意思了

**Comment by langningchen** [comment]
我试试

**Comment by langningchen** [comment]
不是，`master`与`45-feature-request-better-images`是相同的吧？

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/216db0a4-52a8-4cb0-adc4-607627c7acc6)

**Comment by PythonSmall-Q** [comment]
err没有，

**Comment by PythonSmall-Q** [comment]
你把分支里面image地注释关掉就行

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/f39cdd76-a22f-4d41-9a54-d373e74e9bf5)

**Comment by PythonSmall-Q** [comment]
我记得后来把注释戒掉了

**Comment by langningchen** [comment]
哦，好的，我用 Dev 分支的

**Comment by langningchen** [comment]
你发一个预览版本啊

**Comment by langningchen** [comment]
Dev分支的怎么没有发布？

**Comment by PythonSmall-Q** [comment]
有锅，发不了图片

**Comment by PythonSmall-Q** [comment]
上次让boomzero看一下他还没看

**Comment by langningchen** [comment]
哎呦

**Comment by langningchen** [comment]
不是，怎么没有效果呢？

**Comment by PythonSmall-Q** [comment]
咋啦？

**Comment by langningchen** [comment]
根本没有显示 Uploading Image

**Comment by PythonSmall-Q** [comment]
？？？

**Comment by langningchen** [comment]
这样改没错吧？

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/a611746b-4f09-4e6f-8caa-ea7c346893fa)

**Comment by PythonSmall-Q** [comment]
嘿嘿嘿dispatch别接著

**Comment by PythonSmall-Q** [comment]
我之前更新了分支了，把所有地该去掉的注释都去掉了

**Comment by langningchen** [comment]
好了，出了这个

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/d423e78f-9d27-4434-ada2-f85bd6f1c7ae)

**Comment by langningchen** [comment]
错误的原因是字符串不支持 `-=` 运算符，只支持 `+=`

**Comment by PythonSmall-Q** [comment]
err那咋吧

**Comment by PythonSmall-Q** [comment]
炸（……

**Comment by langningchen** [comment]
怎么 Upload Failed 了

**Comment by langningchen** [comment]
现在又卡在了 `![Uploading Image...]`

**Comment by langningchen** [comment]
哦

**Comment by langningchen** [comment]
好了，我修好了

**Comment by PythonSmall-Q** [comment]
哈？upload failed不可能出来的我把它注释掉了

**Comment by langningchen** [comment]
我把它反注释了

**Comment by PythonSmall-Q** [comment]
所以现在是什么情况

**Comment by PythonSmall-Q** [comment]
能穿了吗？

**Comment by langningchen** [comment]
当然可以

**Comment by langningchen** [comment]
在光标位置插入我也弄好了

**Comment by PythonSmall-Q** [comment]
ok谢谢

**Comment by langningchen** [comment]
> 顺便问一下不能`-=`那怎样删掉部分内容

你自己好好想想

**Comment by PythonSmall-Q** [comment]
喵呜~lnc好强

**Comment by PythonSmall-Q** [comment]
我是废物

**Comment by langningchen** [comment]
Doge

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/7f86a31e-988f-4380-af26-0b7dd9463ac7)
问一下为什么这样不能恢复到原来输入的内容，（就是说没办法去掉uploading image

**Comment by langningchen** [comment]
他是一个指针

**Comment by PythonSmall-Q** [comment]
errrrrrrrr

**Comment by PythonSmall-Q** [comment]
艹

**Comment by langningchen** [comment]
https://blog.csdn.net/icemwj/article/details/119782133

**Comment by langningchen** [comment]
可以参考一下这篇文章

**Comment by langningchen** [comment]
dispatch 我也写好了

**Comment by langningchen** [comment]
效果给你看一下

**Comment by langningchen** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/410dc98d-0e7b-4a29-96ea-828218b4a92a

**Comment by PythonSmall-Q** [comment]
艹没看懂（我是傻子

**Comment by PythonSmall-Q** [comment]
> Recording.2023-10-04.104843.mp4

哇效果真好！！！

**Comment by langningchen** [comment]
我也没看懂，就是你知道他是类似于指针的东西就好了

**Comment by langningchen** [comment]
> > Recording.2023-10-04.104843.mp4
> 
> 哇效果真好！！！

你要吗？

**Comment by PythonSmall-Q** [comment]
还是喜欢c++，可以写强制转换

**Comment by PythonSmall-Q** [comment]
可以呀

**Comment by PythonSmall-Q** [comment]
（狂喜

**Comment by langningchen** [comment]
> 还是喜欢c++，可以写强制转换

所以我就说你去用 TypeScript ，而不是 JavaScript ，前者对类型要求更严格

**Comment by langningchen** [comment]
> 可以呀

我都已经是`前开发者`，说了不帮你们干活了……这怎么办？

**Comment by PythonSmall-Q** [comment]
我去改badge成开发者

**Comment by PythonSmall-Q** [comment]
要不就技术顾问吧

**Comment by PythonSmall-Q** [comment]
（没有工资的那种，就像kkksc03一样

**Comment by langningchen** [comment]
你看[TypeScript官网](https://www.typescriptlang.org/)，第一句话就是 TypeScript is **JavaScript with syntax for types**.

**Comment by PythonSmall-Q** [comment]
hh

> 你看[TypeScript官网](https://www.typescriptlang.org/)，第一句话就是 TypeScript is **JavaScript with syntax for types**.

**Comment by langningchen** [comment]
> （没有工资的那种，就像kkksc03一样

那不太行，我要工资 QAQ

**Comment by PythonSmall-Q** [comment]
赞助分30%给你（？

**Comment by PythonSmall-Q** [comment]
（鸽子开始画大饼

**Comment by langningchen** [comment]
问题是有赞助吗？

**Comment by PythonSmall-Q** [comment]
可能有吧

**Comment by langningchen** [comment]
《可能》

**Comment by langningchen** [comment]
《真·可能》

**Comment by langningchen** [comment]
要么这样，你同意与我开发其他项目，我就给你我改的代码

**Comment by PythonSmall-Q** [comment]
可以。

**Comment by PythonSmall-Q** [comment]
（黑市交易

**Comment by langningchen** [comment]
比如你去用 https://github.com/langningchen/OJTool

**Comment by langningchen** [comment]
~~刚才家长来了~~

**Comment by langningchen** [comment]
```javascript
ContentElement.addEventListener("paste", (EventData) => {
    let Items = EventData.clipboardData.items;
    if (Items.length !== 0) {
        for (let i = 0; i < Items.length; i++) {
            if (Items[i].type.indexOf("image") != -1) {
                let Reader = new FileReader();
                Reader.readAsDataURL(Items[i].getAsFile());
                Reader.onload = () => {
                    let Before = ContentElement.value.substring(0, ContentElement.selectionStart);
                    let After = ContentElement.value.substring(ContentElement.selectionEnd, ContentElement.value.length);
                    const UploadMessage = "![正在上传图片...]()";
                    ContentElement.value = Before + UploadMessage + After;
                    ContentElement.dispatchEvent(new Event("input"));
                    RequestAPI("UploadImage", {
                        "Image": Reader.result
                    }, (ResponseData) => {
                        if (ResponseData.Success) {
                            ContentElement.value = Before + `![](https://api.xmoj-bbs.tech/GetImage?ImageID=${ResponseData.Data.ImageID})` + After;
                            ContentElement.dispatchEvent(new Event("input"));
                        }
                        else {
                            ContentElement.value = Before + `![上传失败！]()` + After;
                            ContentElement.dispatchEvent(new Event("input"));
                        }
                    });
                };
            }
        }
    }
});
```

**Comment by PythonSmall-Q** [comment]
艹模拟赛不会做。乱胡了一个上去

**Comment by langningchen** [comment]
怎么样？能用吗？

**Comment by PythonSmall-Q** [comment]
我试试

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/5a13b52f-2db5-4729-aab5-83528423afaf)
err图片加载不出来。你看看能加在吗？

**Comment by langningchen** [comment]
拷给我

**Comment by langningchen** [comment]
我不愿意手动打 ImageID

**Comment by PythonSmall-Q** [comment]
![](https://api.xmoj-bbs.tech/GetImage?ImageID=nmbfxtzvlheoncxmtczzprukqiyuddzy)

**Comment by langningchen** [comment]
哦，出来了

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/e35251e1-2b7e-4e68-a494-87717253dcb9)

**Comment by PythonSmall-Q** [comment]
艹那就是我的问题了

**Comment by langningchen** [comment]
没什么问题啊？

**Comment by PythonSmall-Q** [comment]
嗯我也加载出来了。前面网炸了

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/d8b5a4e9-8ae6-49ed-a90d-441d18d848bd)

从哪里找的图片？

**Comment by PythonSmall-Q** [comment]
cz地头图

**Comment by PythonSmall-Q** [comment]
评论嵌入会有一点点问题，重复paste，在修锅

**Comment by langningchen** [comment]
我去看看

**Comment by PythonSmall-Q** [comment]
你看那个分支里的代码

**Comment by langningchen** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/ca2bb8ff-1f71-4e2c-9f03-05e2e0ee083d)

**Comment by PythonSmall-Q** [comment]
欸对

**Comment by PythonSmall-Q** [comment]
> 你看那个分支里的代码

帮我看看哪里该出锅了

**Comment by langningchen** [comment]
哪个分支？

**Comment by PythonSmall-Q** [comment]
image那个

**Comment by langningchen** [comment]
https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/7b753903-06c6-4f98-893e-a72449e71ea4

WTF?

**Comment by PythonSmall-Q** [comment]
对就是这个问题

**Comment by langningchen** [comment]
这是因为 addEventListener 次数太多了

**Comment by langningchen** [comment]
她在 add 的时候不会清除原本的 EventListener

**Comment by PythonSmall-Q** [comment]
那咋整？

**Comment by langningchen** [comment]
4109 写错了

**Comment by langningchen** [comment]
4149

**Comment by langningchen** [comment]
因该是ContentEditor而不是ContentElement，包括后面几行都要改

**Comment by PythonSmall-Q** [comment]
wc，没看到

**Comment by langningchen** [comment]
所以上面每一个回复，就给底下的回复框添加了一次 EventListener ，导致最下面事件触发了很多次

**Comment by PythonSmall-Q** [comment]
ok

**Comment by PythonSmall-Q** [comment]
编辑地话会删除所有地内容

**Comment by langningchen** [comment]
> 编辑地话会删除所有地内容 ？

**Comment by langningchen** [comment]
之前那个 BUG 修好了没？

**Comment by PythonSmall-Q** [comment]
哪个？

**Comment by langningchen** [comment]
多次上传的

**Comment by PythonSmall-Q** [comment]
修了

**Comment by langningchen** [comment]
不在 Image 分支吧？

**Comment by PythonSmall-Q** [comment]
更新了忘记穿了

**Comment by PythonSmall-Q** [comment]
核对了一下，没有拼写错误

**Comment by langningchen** [comment]
拼写错误？

**Comment by PythonSmall-Q** [comment]
现在是编辑之后所有内容消失，然后只剩下图片地锅

**Comment by langningchen** [comment]
哦，复现了

**Comment by langningchen** [comment]
你自己查一查

**Comment by langningchen** [comment]
> 因该是ContentEditor而不是ContentElement，包括后面几行都要改

你查一查改全了没有

**Comment by langningchen** [comment]
能不能仔细一点，怎么什么都要问我 QWQ  （

**Comment by PythonSmall-Q** [comment]
@langningchen 你看看能不能更新

**Comment by langningchen** [comment]
@PythonSmall-Q 从哪个版本更新？我现在是开发者模式，因为当时你要让我帮你调试

**Comment by boomzero** [comment]
什么啊
