### ISSUE TITLE
当 Issue 关闭后自动删除 investigating 和 working-on-it 标签

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#83]

**Comment by PythonSmall-Q** [comment]
ohhh修完了！！！

**Comment by langningchen** [comment]
@PythonSmall-Q @boomzero 你们以后还是要 Link branch ，或者给一个 Reference ，像这个，Comment 或者 PR Reference 我都找不到，所以我都不知道你是怎么实现这个功能的，到底改了哪些代码

**Comment by langningchen** [comment]
只有一堆 github-actions 的加标签、删评论的东西
