### ISSUE TITLE
[Feature Request] 代码补全

### ISSUE THREAD

**Issue by boomzero** [XMOJ-Script-dev/XMOJ-Script#86]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

https://github.com/langningchen/XMOJ-Script/issues/572#issue-1920264981

**Comment by PythonSmall-Q** [comment]
triage 如果要的话你来做吧

**Comment by PythonSmall-Q** [comment]
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/debc2738-29c1-4ddd-b504-375cf9e4b08e)
 @boomzero 原文，so不做
/wontfix
