### ISSUE TITLE
[Bug]联想浏览器html兼容性

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#89]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

联想浏览器特有的bug，markdown会显示错误
![original_77723d35974f0be506f60085a7df87ff](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/106425289/4fa32c98-7a74-44ed-95e1-e0830119253d)
图片来自chenzerui

**Comment by PythonSmall-Q** [comment]
解决方案：结束对联想浏览器的支持
理由：联想浏览器对于tampermonkey有很多的限制
讨论一下 @boomzero

**Comment by PythonSmall-Q** [comment]
@XMOJ-Script-dev/infrastructure  @XMOJ-Script-dev/product-managers

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by PythonSmall-Q** [comment]
/-working-on-it

**Comment by boomzero** [comment]
垃圾国产浏览器

**Comment by boomzero** [comment]
但是确实垃圾
