### ISSUE TITLE
[Bug] 复制按钮出错

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#9]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/PythonSmall-Q/XMOJ-Script/assets/106425289/520306b7-b1d5-42c0-8b91-5582802f817e)

**Comment by PythonSmall-Q** [comment]
https://github.com/PythonSmall-Q/XMOJ-Script/issues/23

**Comment by PythonSmall-Q** [comment]
@boomzero 在吗？

**Comment by boomzero** [comment]
刷新一下?

**Comment by boomzero** [comment]
等一下就好了
