### ISSUE TITLE
[Bug] 高亮没了

### ISSUE THREAD

**Issue by langningchen** [XMOJ-Script-dev/XMOJ-Script#92]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug 。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一 Bug 未被提交过。

### 描述

讨论中的代码块高亮没了

![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/81672884/8986b720-da6c-4a34-8b69-076e06aaa031)

### 重现步骤

讨论： http://www.xmoj.tech/discuss3/thread.php?tid=198

**Comment by langningchen** [comment]
@boomzero 你干了没有？就 Close

**Comment by langningchen** [comment]
干了为什么没有连接到分支，也没有提及这个 Issue 的任何 Commit 或者 PR

**Comment by boomzero** [comment]
我只是没写issue编号而已...

**Comment by boomzero** [comment]
> @boomzero 你干了没有？就 Close

~你自己看一眼修了没有不就行了吗...~

**Comment by langningchen** [comment]
是你这样不太符合规范 ~~不过我原来的规范你们也不用了~~ @boomzero
