### ISSUE TITLE
[Feature Request] 分离预览版api和发行版api

### ISSUE THREAD

**Issue by PythonSmall-Q** [XMOJ-Script-dev/XMOJ-Script#93]
### 检查项

- [X] 我已确认了XMOJ增强脚本已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/XMOJ-Script-dev/XMOJ-Script/issues) 中搜索，确认了这一提案未被提交过。

### 描述

在更新workers的时候减少影响，类分布式部署

**Comment by PythonSmall-Q** [comment]
在做了

**Comment by PythonSmall-Q** [comment]
/-investigating /working-on-it

**Comment by boomzero** [comment]
你本地`wrangler dev`不就行了

**Comment by boomzero** [comment]
.

**Comment by boomzero** [comment]
没有必要吧

**Comment by PythonSmall-Q** [comment]
好吧，那就不做了
